package com.regnosys.rosetta.generator.java.template.model;

import java.util.List;

/**
 * Template model for the complete POJO file generated by {@code ModelObjectGenerator}.
 *
 * <p>The template ({@code java-pojo.stg}) handles file-level assembly:
 * package declaration, imports, and class body. The class body is pre-computed
 * in Java because the POJO's 4 nested classes have intricate blank-line
 * whitespace patterns that require exact control for D11 byte-identity.
 */
public class PojoTemplateModel {

    private final String packageName;
    private final List<String> imports;
    private final List<String> staticImports;
    private final String body;

    public PojoTemplateModel(String packageName, List<String> imports,
                              List<String> staticImports, String body) {
        this.packageName = packageName;
        this.imports = List.copyOf(imports);
        this.staticImports = staticImports != null ? List.copyOf(staticImports) : List.of();
        this.body = body;
    }

    public String getPackageName() { return packageName; }
    public List<String> getImports() { return imports; }
    public List<String> getStaticImports() { return staticImports; }
    public String getBody() { return body; }
}
