package com.regnosys.rosetta.harness.jqwik;

import net.jqwik.api.Arbitraries;
import net.jqwik.api.Arbitrary;
import net.jqwik.api.Tuple;

import java.util.List;

/**
 * Jqwik arbitraries that emit syntactically valid {@code .rosetta} source
 * fragments for hot grammar productions.
 *
 * <p>P1.2 audit hook H17 (foundation). This class owns primitive generators
 * — identifiers, string literals, integer literals — and composes them into
 * top-level-production generators. Hot productions land in this order as
 * separate sub-hooks:
 * <ol>
 *   <li>{@code enumDecl} — H17 bootstrap (this file)</li>
 *   <li>{@code typeDecl} — H17.2</li>
 *   <li>{@code funcDecl} — H17.3</li>
 *   <li>{@code ruleDecl} — H17.4</li>
 *   <li>{@code reportDecl} — H17.5</li>
 *   <li>{@code expression} — H17.6</li>
 * </ol>
 *
 * <p>The generators deliberately emit a narrow, stable subset of what the
 * grammar accepts — enough to drive property tests (parse stability,
 * idempotent re-parse) without flooding them with edge cases the grammar
 * itself should cover via the corpus. A wider ATN-driven generator is a
 * separate hook (H18).
 *
 * <p>No regex on structured content: every fragment is assembled from
 * literal string constants and typed {@link Arbitrary} composition.
 */
public final class RuneArbitraries {

    private RuneArbitraries() {}

    /** A reserved-word set we avoid when picking identifier characters. */
    private static final List<String> RESERVED_PREFIXES = List.of(
            "enum", "type", "func", "rule", "report", "namespace", "import",
            "if", "then", "else", "true", "false", "and", "or"
    );

    /**
     * {@code validID}: a Rosetta identifier — one uppercase ASCII letter
     * followed by 2..7 ASCII alphanumerics. Uppercase-first avoids the
     * reserved-word overlap for the primitive form used by this hook.
     */
    public static Arbitrary<String> identifier() {
        Arbitrary<Character> first = Arbitraries.chars().range('A', 'Z');
        Arbitrary<String> tail = Arbitraries.strings()
                .withCharRange('a', 'z')
                .withCharRange('A', 'Z')
                .withCharRange('0', '9')
                .ofMinLength(2)
                .ofMaxLength(7);
        return first.flatMap(f -> tail.map(t -> f + t));
    }

    /**
     * A lowercase-first identifier suitable for enum values and attribute
     * names (e.g. {@code tradeId}). 3..8 ASCII alphanumerics total.
     */
    public static Arbitrary<String> lowerIdentifier() {
        Arbitrary<Character> first = Arbitraries.chars().range('a', 'z');
        Arbitrary<String> tail = Arbitraries.strings()
                .withCharRange('a', 'z')
                .withCharRange('0', '9')
                .ofMinLength(2)
                .ofMaxLength(7);
        return first.flatMap(f -> tail.map(t -> f + t))
                .filter(id -> RESERVED_PREFIXES.stream().noneMatch(id::equals));
    }

    /**
     * An enum declaration. Emits:
     * <pre>
     * enum &lt;Name&gt;:
     *     VALUE_ONE
     *     VALUE_TWO
     * </pre>
     * with 1..5 values drawn from {@link #enumValueName()}.
     */
    public static Arbitrary<String> enumDecl() {
        return identifier().flatMap(name ->
                enumValueName().list().ofMinSize(1).ofMaxSize(5)
                        .map(values -> {
                            StringBuilder sb = new StringBuilder();
                            sb.append("enum ").append(name).append(":\n");
                            for (String v : values) sb.append("    ").append(v).append('\n');
                            return sb.toString();
                        }));
    }

    /** An enum value name: UPPER_SNAKE_CASE, 2..4 segments of 2..6 uppercase letters. */
    public static Arbitrary<String> enumValueName() {
        Arbitrary<String> segment = Arbitraries.strings()
                .withCharRange('A', 'Z')
                .ofMinLength(2).ofMaxLength(6);
        return segment.list().ofMinSize(1).ofMaxSize(4)
                .map(parts -> String.join("_", parts));
    }

    /**
     * A full {@code rosettaModel}: {@code namespace} header plus one
     * root element generated by {@code body}. The namespace itself is a
     * fixed {@code test.generated} to keep property tests focused on the
     * body production.
     */
    public static Arbitrary<String> modelWith(Arbitrary<String> body) {
        return body.map(b -> "namespace test.generated\n\n" + b);
    }

    /** A type name drawn from a small whitelist of built-in-style names. */
    public static Arbitrary<String> simpleTypeName() {
        return Arbitraries.of("string", "int", "number", "boolean", "date", "time");
    }

    /**
     * A single attribute line: {@code name TypeName (1..1)}. Cardinality is
     * always the simplest form to keep the generator deterministic.
     */
    public static Arbitrary<String> attribute() {
        return lowerIdentifier().flatMap(name ->
                simpleTypeName().map(ty -> "    " + name + " " + ty + " (1..1)"));
    }

    /**
     * A {@code dataType} (type declaration). Zero to four attributes. No
     * inheritance, no annotations, no conditions — those are deliberately
     * out of scope for the bootstrap arbitrary to keep the generated
     * surface tight. Broader surface moves to H18 (ATN-driven generic).
     */
    public static Arbitrary<String> typeDecl() {
        return identifier().flatMap(name ->
                attribute().list().ofMinSize(0).ofMaxSize(4)
                        .map(attrs -> {
                            StringBuilder sb = new StringBuilder();
                            sb.append("type ").append(name).append(":\n");
                            for (String a : attrs) sb.append(a).append('\n');
                            return sb.toString();
                        }));
    }

    /** An attribute with no leading indent — used inside {@code inputs:} / {@code output:}. */
    private static Arbitrary<String> unindentedAttribute() {
        return lowerIdentifier().flatMap(name ->
                simpleTypeName().map(ty -> name + " " + ty + " (1..1)"));
    }

    /**
     * A {@code function} declaration. Generates either a bare
     * {@code func Name:} or a full {@code inputs: / output:} pair. No
     * conditions, operations, or post-conditions — those are future hooks.
     */
    public static Arbitrary<String> funcDecl() {
        Arbitrary<String> bare = identifier().map(n -> "func " + n + ":\n");
        Arbitrary<String> full = identifier().flatMap(name ->
                unindentedAttribute().list().ofMinSize(1).ofMaxSize(3).flatMap(inputs ->
                        unindentedAttribute().map(output -> {
                            StringBuilder sb = new StringBuilder();
                            sb.append("func ").append(name).append(":\n");
                            sb.append("    inputs:\n");
                            for (String in : inputs) sb.append("        ").append(in).append('\n');
                            sb.append("    output:\n");
                            sb.append("        ").append(output).append('\n');
                            return sb.toString();
                        })));
        return Arbitraries.oneOf(bare, full);
    }

    /**
     * A {@code rosettaRule} — either a {@code reporting rule} or an
     * {@code eligibility rule}. No FROM clause, no expression body — the
     * bootstrap keeps the generator tight. Expression-body rules move to
     * H17.6 alongside the expression generator.
     */
    public static Arbitrary<String> ruleDecl() {
        Arbitrary<String> kind = Arbitraries.of("reporting", "eligibility");
        return kind.flatMap(k -> identifier().map(name ->
                k + " rule " + name + ":\n"));
    }

    /** A reporting cadence from the closed lexer set. */
    private static final Arbitrary<String> REPORTING_CADENCE =
            Arbitraries.of("real-time", "T+1", "T+2", "T+3", "T+4", "T+5", "ASATP");

    /**
     * A {@code rosettaReport}. Minimal report per grammar:
     * <pre>
     * report &lt;Body&gt; &lt;Corpus&gt; in &lt;cadence&gt; from &lt;SourceType&gt; when &lt;Condition&gt; with type &lt;Report&gt;
     * </pre>
     * Body/Corpus/SourceType/Condition/Report are generated identifiers; the
     * parser only needs them to be lexically valid.
     */
    public static Arbitrary<String> reportDecl() {
        return identifier().flatMap(body ->
                identifier().flatMap(corpus ->
                        REPORTING_CADENCE.flatMap(cadence ->
                                identifier().flatMap(src ->
                                        identifier().flatMap(cond ->
                                                identifier().map(ty ->
                                                        "report " + body + " " + corpus
                                                                + " in " + cadence
                                                                + " from " + src
                                                                + " when " + cond
                                                                + " with type " + ty + "\n"))))));
    }

    // ========================================================================
    // H17.6 — expression arbitrary
    // ========================================================================
    // The expression rule in RosettaParser.g4 has 91 labelled alternatives
    // (binary ops, postfix ops, primary forms, "without-left" statement
    // variants, prefix unary). Emitting every alternative with a hand-rolled
    // arbitrary would balloon this class; instead, we cover the **hot shapes**
    // and let the forthcoming H18.2 ATN-walker pick up the long tail under
    // a separate PR.
    //
    // Coverage targeted by this bootstrap (all are labelled alternatives in
    // RosettaParser.g4:251-352):
    //   LiteralExpr (int/string/bool/empty), SymbolRefExpr, ParenExpr,
    //   ListLiteralExpr, ConditionalExpr, AdditiveExpr, MultiplicativeExpr,
    //   ComparisonExpr, EqualityExpr, AndExpr, OrExpr, FeatureCallExpr,
    //   ExistsExpr, CountExpr, FlattenExpr, DistinctExpr, ReverseExpr,
    //   FirstExpr, LastExpr, SumExpr, OnlyElementExpr, ToStringExpr,
    //   ToNumberExpr.
    //
    // Depth is bounded by an integer parameter decremented on every recursive
    // call. At depth 0 only primary alternatives are emitted, so the
    // arbitrary is total without needing Arbitraries.lazy.
    // ========================================================================

    /** Max recursion depth used by {@link #expressionInFunctionBody()}. */
    public static final int DEFAULT_EXPRESSION_DEPTH = 3;

    /**
     * An {@code expression} fragment with recursion bounded by {@code maxDepth}.
     * At {@code maxDepth == 0} only primary (non-recursive) forms are emitted,
     * so the arbitrary terminates without using {@link Arbitraries#lazy}.
     */
    public static Arbitrary<String> expression(int maxDepth) {
        Arbitrary<String> primary = primaryExpr();
        if (maxDepth <= 0) return primary;
        int next = maxDepth - 1;
        return Arbitraries.frequencyOf(
                // Weight primaries high so expressions stabilise fast —
                // property-test runtime grows roughly with depth, and deep
                // stacks over-shrink on failure.
                Tuple.of(6, primary),
                Tuple.of(2, binaryExpr(next)),
                Tuple.of(1, postfixExpr(next)),
                Tuple.of(1, featureCallExpr(next)),
                Tuple.of(1, conditionalExpr(next)),
                Tuple.of(1, parenExpr(next)),
                Tuple.of(1, listLiteralExpr(next))
        );
    }

    /**
     * Wraps a generated expression in a minimal parseable function so it can
     * be fed to {@code RosettaParserFacade.parseString}. Uses a
     * {@code shortcutDeclaration} ({@code alias X: <expr>}) because that's
     * the smallest grammar context that holds an {@code expression} without
     * requiring an {@code inputs:} / {@code output:} block (RosettaParser.g4:214).
     */
    public static Arbitrary<String> expressionInFunctionBody() {
        return modelWith(expression(DEFAULT_EXPRESSION_DEPTH).map(e ->
                "func TestExpr:\n    alias X: " + e + "\n"));
    }

    // ---- primary expression forms ----

    private static Arbitrary<String> primaryExpr() {
        // Primaries are the base cases that terminate recursion. Split into
        // literals, references, and the `empty` keyword to hit both
        // LiteralExpr and SymbolRefExpr labels from the grammar.
        return Arbitraries.frequencyOf(
                Tuple.of(3, intLiteral()),
                Tuple.of(3, identifier()),
                Tuple.of(1, boolLiteral()),
                Tuple.of(1, stringLiteral()),
                Tuple.of(1, Arbitraries.just("empty"))
        );
    }

    private static Arbitrary<String> intLiteral() {
        // RosettaLexer INT_LITERAL : DIGIT+ (non-negative). Prefix unary
        // minus is a separate expression alternative; emitting it as part
        // of the literal itself would double-count.
        return Arbitraries.integers().between(0, 9999).map(Object::toString);
    }

    private static Arbitrary<String> boolLiteral() {
        // RosettaLexer 148-149: TRUE : 'True' ; FALSE : 'False' ; —
        // capitalised first letter, not lowercase.
        return Arbitraries.of("True", "False");
    }

    private static Arbitrary<String> stringLiteral() {
        return Arbitraries.strings()
                .withCharRange('a', 'z')
                .ofMinLength(1).ofMaxLength(10)
                .map(s -> "\"" + s + "\"");
    }

    // ---- compound expression forms ----

    private static Arbitrary<String> binaryExpr(int maxDepth) {
        // Covers AdditiveExpr, MultiplicativeExpr, ComparisonExpr,
        // EqualityExpr, AndExpr, OrExpr. Operator spellings verified
        // against RosettaLexer.g4:
        //   PLUS='+', MINUS='-', STAR='*', SLASH='/',
        //   EQ='=', NEQ='<>', LT='<', GT='>', LTE='<=', GTE='>=',
        //   AND='and', OR='or'.
        Arbitrary<String> op = Arbitraries.of(
                "+", "-", "*", "/",
                "=", "<>", "<", ">", "<=", ">=",
                "and", "or");
        return expression(maxDepth).flatMap(lhs ->
                op.flatMap(o ->
                        expression(maxDepth).map(rhs -> lhs + " " + o + " " + rhs)));
    }

    private static Arbitrary<String> postfixExpr(int maxDepth) {
        // Covers ExistsExpr, CountExpr, FlattenExpr, DistinctExpr,
        // ReverseExpr, FirstExpr, LastExpr, SumExpr, OnlyElementExpr,
        // ToStringExpr, ToNumberExpr. Single-keyword suffixes only —
        // alternatives requiring arguments (ChoiceExpr, SwitchExpr,
        // ReduceExpr) are out of scope for the bootstrap.
        Arbitrary<String> suffix = Arbitraries.of(
                "exists", "count", "flatten", "distinct", "reverse",
                "first", "last", "sum", "only-element",
                "to-string", "to-number");
        return expression(maxDepth).flatMap(e -> suffix.map(s -> e + " " + s));
    }

    private static Arbitrary<String> featureCallExpr(int maxDepth) {
        // FeatureCallExpr: expression ARROW validID.
        return expression(maxDepth).flatMap(e ->
                lowerIdentifier().map(f -> e + " -> " + f));
    }

    private static Arbitrary<String> conditionalExpr(int maxDepth) {
        return expression(maxDepth).flatMap(cond ->
                expression(maxDepth).flatMap(thenE ->
                        expression(maxDepth).map(elseE ->
                                "if " + cond + " then " + thenE + " else " + elseE)));
    }

    private static Arbitrary<String> parenExpr(int maxDepth) {
        return expression(maxDepth).map(e -> "(" + e + ")");
    }

    private static Arbitrary<String> listLiteralExpr(int maxDepth) {
        // ListLiteralExpr: LBRACK (expression (COMMA expression)*)? RBRACK.
        // Empty list is permitted by the grammar.
        return expression(maxDepth).list().ofMinSize(0).ofMaxSize(3)
                .map(items -> "[" + String.join(", ", items) + "]");
    }
}
