package org.finos.rune.equivalence;

import org.finos.rune.benchmarks.corpus.CorpusClasses;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assumptions.assumeTrue;

/**
 * THE PR-4 DIFFERENTIAL GATE (the plan § 7 step 4; the family-3 widening at PR-8; the
 * WHOLE-MATRIX widening at PR #607): the reference tree vs the OPTIMISED tree — the
 * goldens with the navigation-family FUNCTION files AND (census § 12) the drr RULE
 * files substituted by the {@code rune-ir-java-optimised} emission — pair-executed with
 * ZERO divergence demanded on every blocking observable: O1 structural (incl. the
 * FUNCTION leg's evaluated outputs over strict/null/lenient arms — the leg covers the
 * {@code *.reports.*} rule classes and the report-function composition roots since the
 * § 12 widening), O2 validation text+path, O3 thrown envelopes, and the reference arms.
 * O5 (the API delta) is PUBLISHED in the census lines, never gated (revised
 * requirement 1; expected zero for this body-only family).
 *
 * <p><b>The population is every function-bearing active catalogue cell of the corpus
 * SOT</b> ({@code test-corpus/corpus-cells.tsv}: the ten CDM and ten DRR cells), each
 * compiled against its OWN transitive closure ({@link CorpusClasses#ensureClosureCompiled}
 * — the SOT's {@code resolved} pins, walked transitively; since PR #607 every closure
 * cell is on disk with goldens, the four resolution-only cells' generated by their own
 * toolchains, so cdm 6.20.x compiles WHOLE against rune-fpml 1.5.3 — the {@code cdm/ingest/}
 * exclusion of PR-2..#606 is retired — and drr 5.61.0 against cdm 5.36.0 + iso20022
 * 1.18.0, its real pins). Until #607 the gate ran over the three function-bearing ring
 * cells and none of the 360 band rows v3.1 re-rendered (the C4 item-2 entry census,
 * the development audit "2026-08-28-optimised-gate-band-entry-census"); the band's
 * FUNCTION and RULE files are now pair-executed in every cell that carries them.
 *
 * <p>Corpus-gated AND overlay-gated: the optimised tree is materialized by
 * {@code OptimisedNavigationEmissionTest} (rune-ir-java-optimised) into
 * {@code rune-ir-java-optimised/target/optimised-tree/<cell>} — run that module's
 * suite first; this gate skips (recorded) when the overlay is absent, and the
 * overlay's content stamp forces recompilation here whenever the emission changes.
 *
 * <p>iso20022 / rune-fpml carry no FUNCTION kind (census: FUNCTION face empty) — the
 * belt below MEASURES that over their goldens rather than assuming it — so the family
 * substitutes nothing there; their pair story stays the standing ref≡ref smoke
 * ({@code LegGPairExecutionSmokeTest}).
 */
class OptimisedNavigationPairGateTest {

    private static final int FLIP_WIDTH_CAP = 4;
    private static final int POPULATE_DEPTH = 2;
    private static final int DETAIL_CAP = 25;
    private static final String OVERLAY_LABEL = "optnav";

    /**
     * The corpora whose cells carry the FUNCTION kind (and, for drr, the reporting
     * RULE kind) — the population the optimised emitter re-emits into. The chaos cell
     * (v3.2 PR-2, charter § 5) joins on landing: its seed families cover every
     * rootElement kind, so its goldens carry functions/reports/rules dirs and the
     * belt below would refuse a chaos left outside. The other two corpora are proven
     * function-free by {@link #functionFreeCorporaCarryNoFunctionGoldens}.
     */
    private static final Set<String> FUNCTION_BEARING_CORPORA = Set.of("cdm", "drr", "chaos");

    /** The placeholder argument when the corpus is absent (the gate then skips, recorded). */
    private static final String CORPUS_ABSENT = "(test-corpus absent)";

    static Stream<String> functionBearingCells() {
        if (!CorpusClasses.corpusPresent()) {
            return Stream.of(CORPUS_ABSENT);
        }
        return CorpusClasses.activeCatalogueCells().stream()
                .filter(c -> FUNCTION_BEARING_CORPORA.contains(c.corpus()))
                .map(CorpusClasses.Cell::rel);
    }

    @ParameterizedTest(name = "{0}")
    @MethodSource("functionBearingCells")
    void optimisedPairHasZeroDivergence(String cellRel) throws Exception {
        assumeTrue(CorpusClasses.corpusPresent(), "test-corpus/ absent — local-only gate");
        assumeTrue(!CORPUS_ABSENT.equals(cellRel), "test-corpus/ absent — local-only gate");
        // The cell's transitive closure, each member compiled against its own — the
        // upstream cells stay REFERENCE on both sides (the family re-emits the cell's
        // own functions and rules only; the composite closure is otherwise frozen).
        List<Path> upstream = CorpusClasses.ensureClosureCompiled(cellRel);
        runGate(cellRel, upstream);
    }

    /**
     * THE POPULATION BELT: a corpus left out of the gate must be function-free in
     * FACT — every active catalogue cell outside {@link #FUNCTION_BEARING_CORPORA}
     * has no {@code functions} directory anywhere under its goldens (the kind the
     * emitter re-emits is the kind that directory holds). An absence claimed over
     * an unscanned cell is no absence at all.
     */
    @Test
    void functionFreeCorporaCarryNoFunctionGoldens() throws IOException {
        assumeTrue(CorpusClasses.corpusPresent(), "test-corpus/ absent — local-only gate");
        List<String> scanned = new ArrayList<>();
        for (CorpusClasses.Cell c : CorpusClasses.activeCatalogueCells()) {
            if (FUNCTION_BEARING_CORPORA.contains(c.corpus())) {
                continue;
            }
            Path goldens = goldensRoot(c.rel());
            assertTrue(Files.isDirectory(goldens), c.rel() + ": goldens absent at " + goldens);
            try (Stream<Path> s = Files.walk(goldens)) {
                // The gate substitutes FUNCTION and drr RULE/REPORT files, so the belt
                // proves the absence of BOTH kinds (the review's catch — a corpus with
                // rules but no functions would have passed a functions-only scan).
                List<String> emitterDirs = s.filter(Files::isDirectory)
                        .filter(p -> {
                            String leaf = p.getFileName().toString();
                            return "functions".equals(leaf) || "reports".equals(leaf)
                                    || "rules".equals(leaf);
                        })
                        .map(p -> goldens.relativize(p).toString().replace('\\', '/'))
                        .toList();
                assertTrue(emitterDirs.isEmpty(), c.rel() + ": a corpus outside the gate's"
                        + " population carries FUNCTION/RULE/REPORT goldens — widen"
                        + " FUNCTION_BEARING_CORPORA: " + emitterDirs);
            }
            scanned.add(c.rel());
        }
        assertFalse(scanned.isEmpty(), "the belt scanned no cell — the SOT has no active"
                + " catalogue cell outside the gate's population, so the filter is vacuous");
        System.out.println("[OptimisedNavigationPairGateTest] function-free belt scanned "
                + scanned.size() + " cells: " + scanned);
    }

    private static Path goldensRoot(String cellRel) {
        Path cell = CorpusClasses.repoRoot().resolve("test-corpus").resolve(cellRel)
                .resolve("rosetta-source");
        Path std = cell.resolve("src").resolve("generated").resolve("java");
        return Files.isDirectory(std) ? std
                : cell.resolve("target").resolve("classes").resolve("generated").resolve("java");
    }

    /**
     * THE REQUIRABLE MODE (the review's catch, the #606 {@code -Dcorpus.required}
     * precedent): an unmaterialised overlay SKIPS a cell by default (a fresh clone
     * has no optimised tree), but the receipts chain passes
     * {@code -Doptnav.required=true} so that "20 cells GREEN" can never rest on a
     * skip count nobody read — there the missing tree is a FAILURE.
     */
    private static final boolean OVERLAY_REQUIRED = Boolean.getBoolean("optnav.required");

    private static void runGate(String cell, List<Path> upstream) throws Exception {
        Path overlay = overlayRoot(cell);
        boolean materialised = Files.isDirectory(overlay)
                && Files.isRegularFile(overlay.resolve(".overlay-marker"));
        String absent = "optimised tree not materialized at " + overlay
                + " — run the rune-ir-java-optimised suite first"
                + " (OptimisedNavigationEmissionTest materializes it)";
        if (OVERLAY_REQUIRED) {
            assertTrue(materialised, absent + " [REQUIRED: -Doptnav.required=true]");
        } else {
            assumeTrue(materialised, absent);
        }

        Path ref = CorpusClasses.ensureCompiled(cell, upstream, null);
        Path opt = CorpusClasses.ensureCompiledWithOverlay(cell, upstream, null, overlay,
                OVERLAY_LABEL, chaosDeclaredGoldenFreeRows(cell),
                chaosOptimisedRouteBrokenRows(cell));

        List<Path> refDirs = new ArrayList<>();
        refDirs.add(ref);
        refDirs.addAll(upstream);
        List<Path> optDirs = new ArrayList<>();
        optDirs.add(opt);
        optDirs.addAll(upstream);

        PairHarness.Summary s = PairHarness.run(
                new PairHarness.Config(cell, new PairHarness.Side(refDirs),
                        new PairHarness.Side(optDirs), FLIP_WIDTH_CAP, POPULATE_DEPTH,
                        DETAIL_CAP),
                System.out);

        assertTrue(s.usableTypes > 0, cell + ": zero usable types — census above");
        assertTrue(s.fnClasses > 0, cell + ": the FUNCTION leg found no function classes —"
                + " the family gate would be vacuous");
        assertTrue(s.fnPairsExecuted > 0, cell + ": zero function pairs executed");
        assertTrue(s.fnInstantiable > 0, cell + ": zero instantiable functions");
        assertEquals(0, s.fnSkippedNoInstance,
                cell + ": every function class must instantiate on BOTH sides — a symmetric"
                        + " instantiation regression would silently shrink the execution leg"
                        + " AND the O5 population (Seat-1 #539 F5): " + s.fnSkippedNoInstanceNames);
        // v3.2 seat 10, round 1 (cq SF-7 / spec SF-4): the classes under a functions namespace with NO canonical
        // evaluate on EITHER side are NON-FUNCTIONS (the A8 axis's rival-TYPE validators) — recorded by name by
        // the harness and pinned here as a SET (LAW 73): a third one is loud, and no name filter can drop a
        // class silently (the first cut's `.functions.validation.` exclusion moved fnClasses 1552 -> 1550 with
        // nothing asserting which two left; the reach measured at round 1: the twenty vendored cells UNMOVED).
        java.util.Set<String> declaredNonFunctions = cell.startsWith("chaos/")
                ? CHAOS_DECLARED_NON_FUNCTION_CLASSES : java.util.Set.of();
        assertEquals(declaredNonFunctions, new java.util.TreeSet<>(s.fnNonFunctionNames),
                cell + ": the non-function classes under a functions namespace must equal the DECLARED set"
                        + " exactly (a new member is a census question, a missing one a register movement)");
        assertEquals(0, s.oneSidedBuilds, cell + ": no one-sided builds");
        // v3.2 seat 10 (chaos-1.1.0, D49): THE FIRST BEHAVIOURAL DIVERGENCE the gate has found on the
        // chaos cell since the belt (#607) - DECLARED here as a SET (LAW 73), shrink-only, on the chaos
        // cell alone; every other cell keeps the hard zero. The 18 one-sided outcomes are ONE class:
        // the optimised twin of s25's C25Only (the implicit-item only-exists root - the census's M6)
        // COMPILES and THROWS at runtime (`NoSuchMethodException: C25Paths$C25PathsImpl.getItem.pick.
        // C25OptA()` - the rendered path `item.pick.C25OptA` is not a getter chain the runtime can
        // resolve) where the reference returns a value, on both populated arms over the nine variants
        // whose overlay twin compiles; the default route's twin of the same file does not compile
        // (M6 in the expected-divergence baseline), so this route is the only one that reaches
        // execution. The value / envelope / arm legs stay at zero; a movement either way is loud.
        // v3.2 seat 12 (D52 H3): the 18 arms HEALED - the set is EMPTY since (the javadoc on CHAOS_DECLARED_ONE_SIDED_ARMS
        // below); the chaos cell keeps the hard zero like every vendored cell, the assertion unchanged.
        java.util.Set<String> declaredOneSided = cell.startsWith("chaos/")
                ? CHAOS_DECLARED_ONE_SIDED_ARMS : java.util.Set.of();
        assertEquals(declaredOneSided, new java.util.TreeSet<>(s.fnOneSidedArms),
                cell + ": the one-sided function outcomes must equal the DECLARED set exactly (a"
                        + " missing member is a heal to re-pin, an extra one a NEW behavioural"
                        + " divergence to census - never to absorb)");
        assertEquals(0, s.totalDivergences() - s.fnOneSidedOutcomes,
                cell + ": THE DIFFERENTIAL GATE — ZERO divergence on O1/O2/O3 + arms +"
                        + " the function leg beyond the declared one-sided set (detail lines"
                        + " above); O5 is published in the census lines, never gated");
    }

    /** The chaos-1.1.0 declared NON-FUNCTION classes under a functions namespace (v3.2 seat 10, round 1; the
     *  pair-g2 print's two `fnSkippedNoInstance ... [no canonical evaluate: ref=false opt=false]` lines, never
     *  typed): the A8 axis's rival TYPE's type-format validators on s04 and s32 — the type's POJO / meta / other
     *  validators are register rows (the A8 path clobber + its cascade), so these two are all that compile. */
    private static final java.util.Set<String> CHAOS_DECLARED_NON_FUNCTION_CLASSES =
            java.util.Collections.unmodifiableSet(new java.util.TreeSet<>(List.of(
                    "chaos.s04.a8pkg.functions.validation.C4AddTypeFormatValidator",
                    "chaos.s32.a8pkg.functions.validation.C32TwinTypeFormatValidator")));

    /** The chaos-1.1.0 declared one-sided set - EMPTY since v3.2 seat 12 (PR #633, D52 H3): the 18 arms declared at
     *  seat 10 (the nine C25Only variants x both populated arms - the optimised twin of `ps then extract (item -> pick ->
     *  C25OptA only exists)` compiled and threw `NoSuchMethodException ...getItem.pick.C25OptA()` where the reference
     *  returned a value) were the M6 shape: the parser returned null for an `item ->` only-exists root and every route
     *  wrote the legacy dotted placeholder. H3 builds the item root as a real RImplicitVariable
     *  (AstBuilder.buildOnlyExistsPath), so the optimised route renders `item.<C25Pick>map("getPick", ...)` like the
     *  others and the pair executes to the same value on both arms. The gate's own 'a missing member is a heal to
     *  re-pin' assertion fired at the seat's verify gate (target/v32-seat12-instruments/scratch/t-equivalence-c7.log:
     *  expected the 18, measured NONE) and the set was re-cut FROM THAT PRINT (patch-pair-gate-s12.py). A member
     *  appearing here again is a NEW behavioural divergence to census, never to absorb; the chaos cell keeps the hard
     *  zero of every vendored cell now. */
    private static final java.util.Set<String> CHAOS_DECLARED_ONE_SIDED_ARMS = chaosDeclaredOneSided();

    private static java.util.Set<String> chaosDeclaredOneSided() {
        java.util.Set<String> out = new java.util.TreeSet<>();   // the measured set at the H3 head: none
        return java.util.Collections.unmodifiableSet(out);
    }

    private static Path overlayRoot(String cell) {
        String leaf = cell.substring(cell.lastIndexOf('/') + 1);
        return CorpusClasses.repoRoot().resolve("rune-ir-java-optimised")
                .resolve("target").resolve("optimised-tree").resolve(leaf);
    }

    /**
     * The chaos cell's GOLDEN-FREE rows (v3.2 PR-2, census F13): the fork's optimised
     * route emits the s17 x36enum files upstream never emitted, so the overlay carries
     * files with no golden twin. EXACTLY those rows — the committed
     * {@code chaos-golden-free.txt}, the noGolden CLASS the divergence baseline's
     * format cannot carry per row (the spec review's SF-7: passing the whole baseline
     * licensed 20× more than the golden-free class) — are passed to the overlay
     * compile as its expected-unmatched set; any OTHER unmatched file still fails the
     * path-mismatch guard loud. The register is asserted to be a SUBSET of the
     * baseline by {@code ChaosForkDiagnosticsGateTest.goldenFreeRowsAreDeclaredDivergenceRows}.
     * Read cross-module by path (the #464 no-test-jar law); a malformed or duplicate
     * row FAILS LOUD (the reader-law consistency the code-quality review demanded).
     * Empty for every vendored cell.
     */
    private static Set<String> chaosDeclaredGoldenFreeRows(String cell) {
        if (!cell.startsWith("chaos/")) {
            return Set.of();
        }
        return readRowFile(CorpusClasses.repoRoot().resolve("rune-java-generator")
                .resolve("src").resolve("test").resolve("resources")
                .resolve("chaos-golden-free.txt"), false);
    }

    /**
     * One strict reader law for the committed row files this gate consumes: absence
     * or a duplicate row fails loud, and so does an empty body unless the caller
     * declares the file one whose MEASURED zero precedes the v3.2 close — a
     * silently-narrowed declared set gates nothing. {@code emptyBodyAdmitted} is
     * {@code true} at ONE call site, the optimised-route register (v3.2 seat 6,
     * PR #627): its rows fell to ZERO at the F5 fix while the D11 declared sets still
     * carry rows, and the file stays as the belt (growth = a new optimised-route
     * regression, measured by the overlay census against a declared set of 0) until
     * the close deletes the six sets together. Package-private for the corpus-free
     * witness {@link DeclaredRowFileReaderUnitTest}: an empty body reads as the empty
     * set on the admitted path and still fails on the strict one; absence and a
     * duplicate row fail on both.
     */
    static Set<String> readRowFile(Path file, boolean emptyBodyAdmitted) {
        if (!Files.isRegularFile(file)) {
            throw new IllegalStateException("committed declared-set file missing: " + file
                    + " — broken checkout (committed, never generated)");
        }
        java.util.Set<String> rows = new java.util.TreeSet<>();
        try {
            int lineNo = 0;
            for (String raw : Files.readAllLines(file, java.nio.charset.StandardCharsets.UTF_8)) {
                lineNo++;
                String line = raw.trim();
                if (line.isEmpty() || line.startsWith("#")) continue;
                if (!rows.add(line)) {
                    throw new IllegalStateException(file + ":" + lineNo
                            + " — duplicate declared row: " + line);
                }
            }
        } catch (IOException e) {
            throw new java.io.UncheckedIOException("cannot read " + file, e);
        }
        if (rows.isEmpty() && !emptyBodyAdmitted) {
            throw new IllegalStateException(file + " carries no rows — at v3.2 close the"
                    + " declared sets are DELETED and their tolerances go with them");
        }
        return java.util.Set.copyOf(rows);
    }

    /**
     * The OPTIMISED-ROUTE broken-emission register (census F16): overlay files the
     * fork's optimised emitter renders un-compilably — the pair gate declines their
     * substitution (the class pairs ref-vs-ref, declared and marker-counted), so a
     * broken optimised emission can never abort the whole cell's gate silently OR
     * masquerade as tested. Committed at {@code rune-ir-java-optimised/src/test/
     * resources/chaos-optimised-route-broken.txt}; shrink-only; deleted at v3.2
     * close. The strict reader law of every declared set, with ONE declared
     * exception (v3.2 seat 6, PR #627): the register's rows fell to ZERO at the F5
     * fix — every row was the optimised twin of a declared default-route D11 row
     * and fell with it, NEW-BROKEN 0 at every census — while the D11 sets still
     * carry rows, so an EMPTY body is admitted HERE ALONE (nothing is declined by THIS
     * register: every overlay file in the pair population substitutes and pair-executes
     * - 733 of 758 since v3.2 seat 9 (PR #630, F13 / D48; 720 of 747 at #627); the other
     * 25 never enter the substitution loop for other declared reasons, the
     * noncompiling-goldens register's 24 rows and 1 of the declared golden-free
     * register's 7 rows (p2's {@code C17Act}, the one function-class overlay file the
     * register still carries: p1's {@code C17Which} has a golden since D48 and p2's
     * {@code C17Sift} is refused at {@code ENUM_VALUE_NAME_ECHO}, emitted on neither
     * route), both subtracted identically on the reference side - and the marker carries
     * NO {@code substitutionDeclined} token, which {@code CorpusClasses} prints only
     * when non-zero: {@code sources=6471 substituted=733 overlayFiles=758 register=24
     * unmatchedDeclared=1}, the MEASURED marker file
     * {@code rune-benchmarks/target/corpus-classes/chaos-1.0.0-optnav/.compiled-marker}
     * ({@code chaos-1.1.0-optnav} since v3.2 seat 10, D49 — the cell replaced whole)
     * of the seat-9 pre-commit run (local; its log {@code scratch/t-pairgate-c5a.log}
     * prints the same facts in its own form and the pair population 4,280 seats,
     * divergent 0)) and the file stays as the belt until the
     * close; absence and a duplicate row still fail loud.
     */
    private static Set<String> chaosOptimisedRouteBrokenRows(String cell) {
        if (!cell.startsWith("chaos/")) {
            return Set.of();
        }
        return readRowFile(CorpusClasses.repoRoot().resolve("rune-ir-java-optimised")
                .resolve("src").resolve("test").resolve("resources")
                .resolve("chaos-optimised-route-broken.txt"), true);
    }
}
