package com.regnosys.rosetta.ir.core;

import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;

/**
 * THE EFFECTIVE BASE of a type-alias chain (v3.3 seat 7, PR #643 - the type gate): a {@code typeAlias} reference collapsed,
 * at its use site, to the declaration the chain ends on and the ARGUMENTS in force there after substitution.
 *
 * <p>{@code typeAlias int(digits int, min int, max int): number(digits: digits, fractionalDigits: 0, min: min, max: max)}
 * referenced as {@code int(digits: 3)} collapses to {@code BASIC_TYPE number [digits=3, fractionalDigits=0]};
 * {@code typeAlias Max3Number: int(digits: 3)} referenced bare collapses to the same; {@code typeAlias Max35Text:
 * string(maxLength: 35)} to {@code BASIC_TYPE string [maxLength=35]}; {@code typeAlias ISODate: date} to
 * {@code RECORD_TYPE date []}. The law is the parser's own ({@code TypeAliasSolver.evaluateBodyWithBindings}): a literal
 * argument wins, a parameter passed through by name reads the use-site binding or stays ABSENT, a body naming another alias
 * recurses with the resolved arguments as the new bindings, and the leaf is a builtin by NAME in the shared registry (a
 * model-declared basic / record type is {@code nothing}), or a data type / enum / choice declaration.
 *
 * <p>The alias NAME never reaches a generated byte - the base does - so this is the one fact a backend needs to type a
 * field declared over an alias, and the Java-type reconcile of the D11 gate asserts a Java type derived from it equal to the
 * old generator's own, per reference. The arguments are LITERAL only (a name value is never carried here: an unbound
 * parameter is absent), in the body's own argument order; the record ENFORCES that and the kind's range.
 *
 * @param kind      the leaf declaration's kind: BASIC_TYPE, RECORD_TYPE, STRUCT, ENUM or CHOICE - never TYPE_ALIAS (the chain
 *                  is collapsed) and never META_TYPE / FIELD / a non-type kind
 * @param name      the leaf's own simple name: the registry name the body wrote ({@code number}, {@code int}, {@code string},
 *                  {@code date} ...), {@code nothing} for a model-declared basic / record type, or the declaration's simple name
 * @param namespace the declaring namespace of a STRUCT / ENUM / CHOICE leaf; empty for a builtin
 * @param arguments the effective arguments after substitution, literal, in the body's argument order
 */
public record IREffectiveBase(IRKind kind, String name, Optional<String> namespace, List<IRTypeArgument> arguments) {

    /** The kinds a collapsed chain may end on. */
    public static final Set<IRKind> LEAF_KINDS = Set.of(IRKind.BASIC_TYPE, IRKind.RECORD_TYPE, IRKind.STRUCT, IRKind.ENUM,
            IRKind.CHOICE);

    public IREffectiveBase {
        Objects.requireNonNull(kind, "kind");
        Objects.requireNonNull(name, "name");
        Objects.requireNonNull(namespace, "namespace");
        arguments = List.copyOf(arguments);
        if (!LEAF_KINDS.contains(kind)) {
            throw new IllegalArgumentException("an effective base cannot be of kind " + kind
                    + " - a collapsed alias chain ends on a basic type, a record type, a data type, an enum or a choice");
        }
        if (name.isBlank()) {
            throw new IllegalArgumentException("an effective base needs the leaf's name");
        }
        for (IRTypeArgument argument : arguments) {
            if (argument.nameValue().isPresent()) {
                throw new IllegalArgumentException("effective argument '" + argument.parameter()
                        + "' passes a parameter through by name - an effective base carries literals only (an unbound parameter is absent)");
            }
        }
    }

    /** {@code namespace.name} for a declared leaf; the bare name for a builtin. */
    public String qualifiedName() {
        return namespace.map(ns -> ns.isEmpty() ? name : ns + "." + name).orElse(name);
    }

    /** The literal value of the named argument, with its sign, when stated. */
    public Optional<String> argument(String parameter) {
        for (IRTypeArgument argument : arguments) {
            if (argument.parameter().equals(parameter)) {
                return argument.literalValue().map(v -> argument.negated() ? "-" + v : v);
            }
        }
        return Optional.empty();
    }
}
