package com.regnosys.rosetta.maven;

import com.regnosys.rosetta.generator.java.ir.IRGenerationProviderImpl;
import com.regnosys.rosetta.generator.java.spi.IRGeneration;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.w3c.dom.Document;

import javax.xml.parsers.DocumentBuilderFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeSet;
import java.util.stream.Stream;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * THE PLUGIN ROUTING (v3.3 seat 9, PR #645 commit 14b) — the targeted real invocation of
 * {@link RunePluginRunner} on a purpose-built fixture, once per route, reading what actually
 * ran out of the runner's own log and comparing every generated byte against goldens taken
 * from the UNCHANGED runner at the parent head with both flags off.
 *
 * <p>Four locks:
 * <ol>
 *   <li>flag off — the legacy generator classes, the goldens byte-for-byte, the file sets equal;</li>
 *   <li>{@code -Drosetta.generator.ir=true} — the reference provider RESOLVES (asserted, never
 *       assumed: a missing provider is a broken build, not a skip), the IR-routed classes are
 *       the ones that ran, and NOT ONE BYTE moves;</li>
 *   <li>{@code -Drosetta.generator.ir.optimised=true} — the optimised provider's declines are
 *       preserved through the same seams (every kind but FUNCTION reads its legacy class), and
 *       not one byte moves;</li>
 *   <li>both flags — {@link IRGeneration}'s exclusivity error surfaces THROUGH the runner,
 *       never swallowed by the diagnostic stream or the log.</li>
 * </ol>
 *
 * <p>The isolation law: every property is set and cleared in {@code try / finally}, and
 * {@link IRGeneration}'s lookup cache is flag-guarded, so a resolved provider can never leak
 * into the flag-off lock. Surefire runs ONE sequential JVM — {@link #surefireIsSequential()}
 * refuses the whole class if the module's pom ever declares otherwise.
 */
class RunePluginRunnerRouteTest {

    private static final Path POM = Path.of("pom.xml");
    private static final Path BUILTINS_DIR =
            Path.of("../test-corpus/rune-dsl-builtins/rune-runtime/src/main/resources/model");
    private static final Path FIXTURE = Path.of("src/test/resources/route-fixture/model");
    private static final Path GOLDEN = Path.of("src/test/resources/route-fixture/golden");

    /** The eleven passes' generator classes on the DEFAULT (flag-off) route, label -> names. */
    private static final Map<String, String> LEGACY_GENERATORS = legacyGenerators();
    /** The same passes' classes with the REFERENCE IR route on. */
    private static final Map<String, String> IR_GENERATORS = irGenerators();
    /** The same passes' classes with the OPTIMISED route on — every kind but FUNCTION declines. */
    private static final Map<String, String> OPTIMISED_GENERATORS = optimisedGenerators();
    /** The dispatch each pass takes, one token per named generator — the same on every route. */
    private static final Map<String, String> DISPATCH = dispatch();

    /**
     * The passes IN THE ORDER generateAll runs them. Map.copyOf randomises its iteration order
     * per JVM (the SALT), so iterating a map here would make WHICH label a failure names
     * unpredictable - a lane could not aim at a pass. The order is declared, once, here.
     */
    private static final List<String> PASSES = List.of(
            "ENUM", "POJO", "METAFIELD", "FUNCTION", "ONLY_EXISTS", "CARDINALITY",
            "TYPE_FORMAT", "XMETA", "DEEP_PATH", "DATA_RULE", "PACKAGE_INFO");

    private static Map<String, String> legacyGenerators() {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("ENUM", "EnumGenerator");
        m.put("POJO", "ModelObjectGenerator,ChoiceObjectGenerator,FunctionGenerator,"
                + "RuleGenerator,ReportGenerator,LabelProviderGenerator");
        m.put("METAFIELD", "MetaFieldGenerator");
        m.put("FUNCTION", "FunctionGenerator");
        m.put("ONLY_EXISTS", "OnlyExistsValidatorGenerator");
        m.put("CARDINALITY", "CardinalityValidatorGenerator");
        m.put("TYPE_FORMAT", "TypeFormatValidatorGenerator");
        m.put("XMETA", "ModelMetaGenerator");
        m.put("DEEP_PATH", "DeepPathUtilGenerator");
        m.put("DATA_RULE", "DataRuleGenerator");
        m.put("PACKAGE_INFO", "JavaPackageInfoGenerator");
        return Map.copyOf(m);
    }

    private static Map<String, String> irGenerators() {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("ENUM", "IREnumGenerator");
        m.put("POJO", "IRModelObjectGenerator,IRChoiceObjectGenerator,IRFunctionGenerator,"
                + "RuleGenerator,ReportGenerator,LabelProviderGenerator");
        m.put("METAFIELD", "IRMetaFieldGenerator");
        m.put("FUNCTION", "IRFunctionGenerator");
        m.put("ONLY_EXISTS", "IROnlyExistsValidatorGenerator");
        m.put("CARDINALITY", "IRCardinalityValidatorGenerator");
        m.put("TYPE_FORMAT", "IRTypeFormatValidatorGenerator");
        m.put("XMETA", "IRModelMetaGenerator");
        m.put("DEEP_PATH", "IRDeepPathUtilGenerator");
        m.put("DATA_RULE", "IRDataRuleGenerator");
        m.put("PACKAGE_INFO", "JavaPackageInfoGenerator");
        return Map.copyOf(m);
    }

    private static Map<String, String> optimisedGenerators() {
        Map<String, String> m = new LinkedHashMap<>(LEGACY_GENERATORS);
        // THE DECLINES: OptimisedIRGenerationProviderImpl pins every kind but FUNCTION to its
        // exact legacy class, and FUNCTION to OptimisedFunctionGenerator — BOTH instances of it,
        // the POJO block's collaborator and the workspace-wide pass.
        m.put("POJO", "ModelObjectGenerator,ChoiceObjectGenerator,OptimisedFunctionGenerator,"
                + "RuleGenerator,ReportGenerator,LabelProviderGenerator");
        m.put("FUNCTION", "OptimisedFunctionGenerator");
        return Map.copyOf(m);
    }

    private static Map<String, String> dispatch() {
        Map<String, String> m = new LinkedHashMap<>();
        m.put("ENUM", "seam");
        m.put("POJO", "seam,seam,collaborator,direct,direct,direct");
        m.put("METAFIELD", "seam");
        m.put("FUNCTION", "direct");
        m.put("ONLY_EXISTS", "seam");
        m.put("CARDINALITY", "seam");
        m.put("TYPE_FORMAT", "seam");
        m.put("XMETA", "seam");
        m.put("DEEP_PATH", "seam");
        m.put("DATA_RULE", "direct");
        m.put("PACKAGE_INFO", "direct");
        return Map.copyOf(m);
    }

    @TempDir
    Path tmp;

    private Path builtinsJar;
    private final List<String> logged = new ArrayList<>();

    private final RunePluginRunner.RunnerLog log = new RunePluginRunner.RunnerLog() {
        @Override
        public void info(String message) {
            logged.add("[INFO] " + message);
        }

        @Override
        public void warn(String message) {
            logged.add("[WARNING] " + message);
        }

        @Override
        public void error(String message) {
            logged.add("[ERROR] " + message);
        }
    };

    /**
     * THE REFUSAL. Every lock here mutates JVM-global system properties, so a parallel or
     * forked surefire would make the four routes race each other and the whole class
     * meaningless. The pom is PARSED (never string-scanned) and the two elements that could
     * introduce concurrency are required to be absent anywhere in it.
     */
    @BeforeAll
    static void surefireIsSequential() throws Exception {
        Document pom = DocumentBuilderFactory.newInstance()
                .newDocumentBuilder().parse(POM.toFile());
        for (String element : List.of("parallel", "forkCount", "threadCount", "forkMode")) {
            int found = pom.getElementsByTagName(element).getLength();
            assertEquals(0, found, "REFUSED: rune-maven-plugin/pom.xml declares <" + element
                    + "> — this class mutates JVM-global route flags and requires ONE sequential"
                    + " surefire JVM; remove the element or re-design the class");
        }
    }

    @BeforeEach
    void zipBuiltins() throws IOException {
        Assumptions.assumeTrue(Files.isDirectory(BUILTINS_DIR),
                "builtins corpus absent — route locks skipped (CI / fresh clone)");
        assertTrue(Files.isDirectory(GOLDEN),
                "route-fixture goldens must be committed alongside the fixture");
        builtinsJar = tmp.resolve("rune-runtime-fixture.jar");
        try (ZipOutputStream zip = new ZipOutputStream(Files.newOutputStream(builtinsJar))) {
            for (String name : List.of("annotations.rosetta", "basictypes.rosetta")) {
                zip.putNextEntry(new ZipEntry("model/" + name));
                zip.write(Files.readAllBytes(BUILTINS_DIR.resolve(name)));
                zip.closeEntry();
            }
        }
        logged.clear();
    }

    // ------------------------------------------------------------------
    // (e) the route header's THREE arms, by exact text
    // ------------------------------------------------------------------

    /**
     * THE THIRD ARM. Arms one and two are read end-to-end by (a) / (b) / (c), but the arm that
     * fires when the flag is set and NO provider resolves cannot be produced from inside this
     * surefire JVM: both provider jars are unconditional test-scope dependencies of this module,
     * so providerOrNull() can never answer null with the flag on here. RunePluginRunner#routeLine
     * is a PURE function of those two facts precisely so the arm is still READ rather than
     * assumed - a downgrade that reported the wrong thing would otherwise ship unwitnessed.
     *
     * <p>No assumption guards this test: it touches neither the corpus nor the filesystem.
     */
    @Test
    void theRouteHeaderReadsAllThreeArmsByExactText() {
        assertEquals("ON (provider com.regnosys.rosetta.generator.java.ir.IRGenerationProviderImpl)",
                RunePluginRunner.routeLine(new IRGenerationProviderImpl(), true),
                "the FIRST route arm (a provider resolved) must read exactly");
        assertEquals("OFF (flag -Drosetta.generator.ir=true set but NO provider on the classpath"
                        + " \u2014 Path-1)",
                RunePluginRunner.routeLine(null, true),
                "the THIRD route arm (the flag set, no provider on the classpath) must read"
                        + " exactly - the only reader this arm has");
        assertEquals("OFF", RunePluginRunner.routeLine(null, false),
                "the SECOND route arm (no flag, no provider) must read exactly");
        assertEquals("OFF", RunePluginRunner.routeLine(null, IRGeneration.enabled()),
                "the default route, read through IRGeneration.enabled() itself");
    }

    // ------------------------------------------------------------------
    // (a) the default route
    // ------------------------------------------------------------------

    @Test
    void flagOffRunsTheLegacyClassesAndWritesTheGoldensByteForByte() throws IOException {
        assertNull(System.getProperty(IRGeneration.PROPERTY),
                "precondition: the reference flag is ABSENT on the default route");
        assertNull(System.getProperty(IRGeneration.OPTIMISED_PROPERTY),
                "precondition: the optimised flag is ABSENT on the default route");

        Path out = runFixture("out-off");
        printRoute("(a) flag-off");

        assertRouteLine("OFF");
        assertGenerators(LEGACY_GENERATORS);
        assertGoldensByteForByte(out);
    }

    // ------------------------------------------------------------------
    // (b) the reference IR route
    // ------------------------------------------------------------------

    @Test
    void flagOnSelectsTheIRRoutedClassesAndMovesNotOneByte() throws IOException {
        System.setProperty(IRGeneration.PROPERTY, "true");
        try {
            var provider = IRGeneration.providerOrNull();
            assertNotNull(provider, "the reference IRGenerationProvider MUST resolve on this"
                    + " classpath — rune-ir-java is a test-scope dependency of this module; a"
                    + " missing provider is a broken build, never a skipped lock");
            assertEquals("com.regnosys.rosetta.generator.java.ir.IRGenerationProviderImpl",
                    provider.getClass().getName(), "the reference provider by name");

            Path out = runFixture("out-on");
            printRoute("(b) -Drosetta.generator.ir=true");

            assertRouteLine("ON (provider com.regnosys.rosetta.generator.java.ir"
                    + ".IRGenerationProviderImpl)");
            assertGenerators(IR_GENERATORS);
            assertGoldensByteForByte(out);
        } finally {
            System.clearProperty(IRGeneration.PROPERTY);
        }
    }

    // ------------------------------------------------------------------
    // (c) the optimised route
    // ------------------------------------------------------------------

    @Test
    void optimisedFlagKeepsTheProvidersDeclines() throws IOException {
        System.setProperty(IRGeneration.OPTIMISED_PROPERTY, "true");
        try {
            var provider = IRGeneration.providerOrNull();
            assertNotNull(provider, "the OptimisedIRGenerationProvider MUST resolve on this"
                    + " classpath — rune-ir-java-optimised is a test-scope dependency of this"
                    + " module");
            assertEquals("com.regnosys.rosetta.generator.java.optimised"
                            + ".OptimisedIRGenerationProviderImpl",
                    provider.getClass().getName(), "the optimised provider by name");

            Path out = runFixture("out-opt");
            printRoute("(c) -Drosetta.generator.ir.optimised=true");

            assertRouteLine("ON (provider com.regnosys.rosetta.generator.java.optimised"
                    + ".OptimisedIRGenerationProviderImpl)");
            assertGenerators(OPTIMISED_GENERATORS);
            assertGoldensByteForByte(out);
        } finally {
            System.clearProperty(IRGeneration.OPTIMISED_PROPERTY);
        }
    }

    // ------------------------------------------------------------------
    // (d) both flags
    // ------------------------------------------------------------------

    @Test
    void bothFlagsFailLoudlyThroughTheRunner() {
        System.setProperty(IRGeneration.PROPERTY, "true");
        System.setProperty(IRGeneration.OPTIMISED_PROPERTY, "true");
        try {
            IllegalStateException thrown = assertThrows(IllegalStateException.class,
                    () -> runFixture("out-both"),
                    "both routes selected must fail the plugin run, never downgrade silently");
            assertTrue(thrown.getMessage().contains(IRGeneration.PROPERTY)
                            && thrown.getMessage().contains(IRGeneration.OPTIMISED_PROPERTY),
                    "the exclusivity error must name BOTH properties, got: "
                            + thrown.getMessage());
            assertTrue(logged.stream().noneMatch(l -> l.contains("IR route:")),
                    "the route header must not print a verdict it could not compute, got: "
                            + logged);
        } finally {
            System.clearProperty(IRGeneration.PROPERTY);
            System.clearProperty(IRGeneration.OPTIMISED_PROPERTY);
        }
    }

    // ------------------------------------------------------------------
    // the harness
    // ------------------------------------------------------------------

    private Path runFixture(String outName) throws IOException {
        Path out = tmp.resolve(outName);
        RunePluginRunner.Result result = new RunePluginRunner(
                List.of(FIXTURE),
                List.of(builtinsJar.toAbsolutePath().toString()),
                ".*rune-runtime-fixture\\.jar",
                RosettaConfigFile.defaults(),
                out,
                true,
                log).run();
        assertEquals(0, result.errors(), "the route fixture must link and validate clean, got: "
                + logged);
        assertTrue(result.filesWritten() > 0, "the route fixture must emit");
        return out;
    }

    /**
     * Prints the runner's OWN route header and pass lines for this route, so the run of record
     * carries what actually ran and a reader never has to take the assertions' word for it.
     */
    private void printRoute(String tag) {
        for (String line : logged) {
            if (line.startsWith("[INFO] IR route:") || line.contains(" generator=")) {
                System.out.println("ROUTE " + tag + " " + line);
            }
        }
    }

    /** The plugin's own three-way route header — the pass lines' companion. */
    private void assertRouteLine(String expected) {
        assertTrue(logged.contains("[INFO] IR route: " + expected),
                "expected the route header [INFO] IR route: " + expected + ", got: " + logged);
    }

    /**
     * Every pass's {@code generator=} / {@code dispatch=} tokens, read out of the runner's own
     * log line for that pass — the observable that makes a lying route readable.
     */
    private void assertGenerators(Map<String, String> expected) {
        assertEquals(PASSES.size(), expected.size(), "every pass must have an expected generator");
        for (String label : PASSES) {
            String line = passLine(label);
            assertEquals(expected.get(label), token(line, " generator=", " dispatch="),
                    label + " must name the generator(s) that actually ran, line: " + line);
            assertEquals(DISPATCH.get(label), token(line, " dispatch=", null),
                    label + " must name the dispatch each generator took, line: " + line);
        }
    }

    private String passLine(String label) {
        return logged.stream()
                .filter(l -> l.startsWith("[INFO] " + label + " files="))
                .findFirst()
                .orElseThrow(() -> new AssertionError(
                        "no pass line for " + label + " in: " + logged));
    }

    private static String token(String line, String key, String end) {
        int i = line.indexOf(key);
        assertTrue(i >= 0, "line has no " + key.trim() + ": " + line);
        String rest = line.substring(i + key.length());
        if (end == null) {
            return rest;
        }
        int j = rest.indexOf(end);
        assertTrue(j >= 0, "line has no " + end.trim() + ": " + line);
        return rest.substring(0, j);
    }

    /**
     * THE BYTE PROOF: the generated set and the golden set are equal BOTH WAYS (no extra file,
     * no missing file — the populations printed on failure), and every file's bytes match.
     */
    private static void assertGoldensByteForByte(Path out) throws IOException {
        TreeSet<String> produced = relativeFiles(out);
        TreeSet<String> golden = relativeFiles(GOLDEN);
        assertEquals(golden, produced, "the generated file SET must equal the golden set"
                + " (extra=" + minus(produced, golden) + " missing=" + minus(golden, produced)
                + ")");
        assertTrue(!golden.isEmpty(), "the golden population must not be empty");
        List<String> differing = new ArrayList<>();
        for (String key : golden) {
            byte[] want = Files.readAllBytes(GOLDEN.resolve(key));
            byte[] have = Files.readAllBytes(out.resolve(key));
            if (!java.util.Arrays.equals(want, have)) {
                differing.add(key);
            }
        }
        assertEquals(List.of(), differing,
                "NOT ONE BYTE may move against the parent-head goldens; differing file(s): "
                        + differing);
    }

    private static TreeSet<String> relativeFiles(Path root) throws IOException {
        try (Stream<Path> s = Files.walk(root)) {
            return s.filter(Files::isRegularFile)
                    .map(p -> root.relativize(p).toString().replace('\\', '/'))
                    .sorted(Comparator.naturalOrder())
                    .collect(TreeSet::new, TreeSet::add, TreeSet::addAll);
        }
    }

    private static TreeSet<String> minus(TreeSet<String> a, TreeSet<String> b) {
        TreeSet<String> r = new TreeSet<>(a);
        r.removeAll(b);
        return r;
    }
}
