package com.regnosys.rosetta.generator.java.ir;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.regnosys.rosetta.ast.RRootElement;
import com.regnosys.rosetta.ast.model.RModel;
import com.regnosys.rosetta.ast.types.RChoice;
import com.regnosys.rosetta.ast.types.RDataType;
import com.regnosys.rosetta.ast.types.RTypeAlias;
import com.regnosys.rosetta.generator.GenerationException;
import com.regnosys.rosetta.generator.java.GeneratorModel;
import com.regnosys.rosetta.generator.java.object.ModelObjectGenerator;
import com.regnosys.rosetta.generator.java.types.JavaTypeTranslator;
import com.regnosys.rosetta.generator.java.types.RJavaPojoInterface;
import com.regnosys.rosetta.generator.java.types.JavaTypeUtil;
import com.regnosys.rosetta.ir.adapter.AstToIRAdapter;
import com.regnosys.rosetta.ir.adapter.IRModelNode;
import com.regnosys.rosetta.ir.adapter.IRTypeNode;

/**
 * Path-2 (IR-routed) variant of {@link ModelObjectGenerator} for {@code data}
 * declarations. For each {@link RDataType} it builds the STRUCT IR via
 * {@link AstToIRAdapter} — exercising the adapter over the real corpus and
 * reconciling EVERY fact it carries against the source ({@link IRDeclarationReconciler},
 * decision D55) — then emits byte-identically
 * through the unchanged Path-1 pipeline (decision L-001).
 *
 * <p>THE TYPE ALIAS RIDES THIS PASS (v3.3 seat 7, PR #643 — the type gate). A {@code typeAlias} declaration writes no
 * file of its own — its name never reaches a generated byte, its collapsed BASE does — so it belongs to no emitting
 * generator's population. It is adapted and reconciled here, through a SECOND reconciler with its own counters
 * ({@link #typeAliasReconcileStats()}), so the alias declarations neither join nor disturb the data-type pass's
 * {@code declarations == expected} (LAW 84: each gate asserts its own population). The two reconcilers share ONE
 * adapter instance, so one {@code CorpusResolver} serves both.
 *
 * <p>THE PROPERTY GATE RIDES IT TOO (v3.3 seat 8, PR #644 — PR B, the second zero-byte gate of the strict path). The
 * declaration reconcile above asserts what a declaration DECLARES; the emitter that is coming writes a type's POJO and
 * its per-type DERIVED files (the three validators, {@code *Meta}, the metafield wrappers, {@code package-info}) from
 * facts the declaration alone does not name. Four further surfaces are therefore read here, each through its own
 * reconciler with its own counters and its own D11 line:
 * <ul>
 *   <li>{@link IRPropertyModel} — the POJO property surface (own, all, the re-put order, the compatibility names, the
 *       synthetic meta, the inherited choice options), reconciled property for property against the old generator's own
 *       {@code RJavaPojoInterface} by {@link IRPropertyReconciler} ({@link #propertyReconcileStats()});</li>
 *   <li>{@link IRDerivedFactsReconciler} — the derived files' input facts (the type-format envelope, cardinality,
 *       only-exists, the {@code *Meta} wiring, deep-path eligibility and ORDER, the {@code java.lang} collision law)
 *       ({@link #derivedReconcileStats()});</li>
 *   <li>{@link IRModelReconciler} — the MODEL node itself, the first model-level node the IR carries, against its
 *       {@link RModel} ({@link #modelReconcileStats()});</li>
 *   <li>{@link IRWrapperReconciler} — the metafield WRAPPER spec set, which is a whole-cell fact rather than a
 *       per-declaration one, so it is reconciled ONCE per cell, lazily, when the host first reads
 *       {@link #wrapperReconcileStats()} after the pass ({@link #wrapperMismatches()} names what it found).</li>
 * </ul>
 * The property and derived reads share ONE population — the cell's VALIDATED ELEMENTS, its {@code data} types and its
 * {@code choice}s together — so both book an element BEFORE either half runs: an element whose property model throws is
 * a mismatch on both lines, never a silent drop from either population (LAW 84). The parent chain both surfaces walk is
 * resolved through the workspace-wide {@link IRTypeIndex}, whose parents are reconciled against their own sources by a
 * THIRD reconciler whose counters are kept apart from the pass's ({@link #propertyParentReconcileStats()}) — a parent
 * may live outside the cell's emission filter, so it cannot join {@code declarations == expected}.
 *
 * <p>Used only when {@link IRFlag} is enabled; Path-1 is otherwise untouched.
 * Lab-authored Phase-1 (not present upstream).
 */
public final class IRModelObjectGenerator extends ModelObjectGenerator
        implements IREmittableGenerator {

    private final IRDeclarationReconciler reconciler;
    private final IRDeclarationReconciler aliasReconciler;
    /** The index's own reconciler: every parent it resolves is asserted against its source, its counters apart (LAW 84). */
    private final IRDeclarationReconciler parentReconciler;
    /** The workspace-wide type index: ONE {@link IRTypeNode} per declaration, the parent chain resolved and reconciled. */
    private final IRTypeIndex index;
    private final IRPropertyReconciler propertyReconciler;
    private final IRDerivedFactsReconciler derivedReconciler;
    /** Every model of the workspace as its MODEL node, adapted once in load order - the qualifiable ROOT's IR-side law (PR #644 pre-review MF-2). */
    private final IRModelIndex modelIndex;
    private final IRModelReconciler modelReconciler;
    private final IRWrapperReconciler wrapperReconciler;
    /** Every MODEL node this pass adapted, in pass order — the wrapper reconcile's function-signature / with-meta input. */
    private final List<IRModelNode> emittedModelNodes = new ArrayList<>();
    /** Every STRUCT / CHOICE node this pass read, in pass order — the wrapper reconcile's declaration input. */
    private final List<IRTypeNode> emittedTypeNodes = new ArrayList<>();
    /** The once-per-cell wrapper reconcile's memo: non-null once it has run, so the host's reads are idempotent. */
    private List<String> wrapperReconcileMismatches;
    /**
     * THE POJO SHADOW (v3.3 seat 9, PR #645 commit 4): for every {@code data} declaration this pass saw, what
     * {@link IRDataTypeEmitter} answered when asked for its POJO - keyed by the file's OUTPUT KEY, so the D11 host
     * can find the golden of the same name. NOTHING here reaches the output map: the shadow is asked AFTER the
     * pass's own generation and its answer is never written.
     */
    private final java.util.Map<String, String[]> pojoShadow = new java.util.LinkedHashMap<>();
    /**
     * The generator model this pass was built with - held here because {@code ModelObjectGenerator}'s own copy is
     * private. Read by ONE site: {@link #shadowPojos}, for the {@code doNotPrune} set the POJO emitter's config
     * carries (v3.3 seat 9, PR #645 commit 9).
     */
    private final GeneratorModel generatorModel;
    /**
     * The pass's own {@code JavaTypeUtil} - held here because {@code ModelObjectGenerator}'s copy is private.
     * Read by ONE site: {@link #shadowPojos}, which hands it to {@link IRDataTypeEmitter} so the compat
     * members' coercion algebra arithmetics its types through the SAME model-free table the old route uses
     * (v3.3 seat 9, PR #645 commit 10). It reads no model and no AST node.
     */
    private final JavaTypeUtil typeUtil;

    public IRModelObjectGenerator(GeneratorModel generatorModel, JavaTypeTranslator typeTranslator,
                                  JavaTypeUtil typeUtil) {
        super(generatorModel, typeTranslator, typeUtil);
        this.generatorModel = generatorModel;
        this.typeUtil = typeUtil;
        this.reconciler = new IRDeclarationReconciler(generatorModel);
        // the SAME adapter instance, by construction: one CorpusResolver serves both reconcilers (PR #644, the
        // banked cq NIT-1 of #643 - the second reconciler used to build an adapter it never read)
        this.aliasReconciler = new IRDeclarationReconciler(generatorModel, reconciler.adapter());
        // the index's parents ride a THIRD reconciler on the SAME adapter, for the same reason (v3.3 seat 8, PR #644)
        this.parentReconciler = new IRDeclarationReconciler(generatorModel, reconciler.adapter());
        this.index = new IRTypeIndex(generatorModel.workspace(), reconciler.adapter(), parentReconciler);
        this.propertyReconciler = new IRPropertyReconciler(generatorModel);
        // the model index shares the pass's adapter (one CorpusResolver, one TypeInferrer serve every half); it is
        // built BEFORE the two reconcilers that take it, so neither can be handed a null (v3.3 seat 9, PR #645
        // commit 13: the derived reconcile's qualify-wing family reads it too, and a nullable setter is exactly the
        // silent fallback round 1 of PR #644 refused - MF-2)
        this.modelIndex = new IRModelIndex(generatorModel.workspace(), reconciler.adapter());
        this.derivedReconciler = new IRDerivedFactsReconciler(generatorModel, modelIndex);
        this.modelReconciler = new IRModelReconciler(generatorModel, modelIndex);
        this.wrapperReconciler = new IRWrapperReconciler(generatorModel, typeTranslator, index);
    }

    /**
     * {@code {declarations attempted, facts asserted, mismatches}} of this generator's passes - the D11 host
     * prints the three per cell and asserts the last at zero (v3.3 seat 5, decision D55).
     */
    public int[] declarationReconcileStats() {
        return reconciler.stats();
    }

    /**
     * {@code {declarations attempted, facts asserted, mismatches}} of the {@code typeAlias} declarations this pass
     * reconciled - a population of its own, printed and gated on its own D11 line (v3.3 seat 7, PR #643).
     */
    public int[] typeAliasReconcileStats() {
        return aliasReconciler.stats();
    }

    /**
     * The same three counters for the PROPERTY SURFACE of every validated element (the cell's {@code data} types and
     * {@code choice}s together, ONE population): the {@link IRPropertyModel} built from the IR alone, asserted property
     * for property against the old generator's own {@code RJavaPojoInterface} (v3.3 seat 8, PR #644).
     */
    public int[] propertyReconcileStats() {
        return propertyReconciler.stats();
    }

    /**
     * The same three counters for the PARENTS the {@link IRTypeIndex} resolved behind a {@code baseType} reference -
     * each adapted and reconciled ONCE against its own source, a mismatch or a throw refusing every descendant. Kept
     * apart from the pass's population because a parent may live outside the cell's emission filter (v3.3 seat 8).
     */
    public int[] propertyParentReconcileStats() {
        return parentReconciler.stats();
    }

    /**
     * The same three counters for the DERIVED-FILE FACTS of every validated element - the type-format envelope, the
     * cardinality bounds, the only-exists members, the {@code *Meta} wiring, deep-path eligibility and order, and the
     * {@code java.lang} collision law - over the same population as {@link #propertyReconcileStats()} (v3.3 seat 8).
     */
    public int[] derivedReconcileStats() {
        return derivedReconciler.stats();
    }

    /**
     * The same three counters for the MODEL nodes this pass adapted - one per emitted {@link RModel} - carrying the
     * model's definition and version, its qualifiable configs and qualification functions, every function signature and
     * every {@code with-meta} use (v3.3 seat 8, PR #644).
     */
    public int[] modelReconcileStats() {
        return modelReconciler.stats();
    }

    /**
     * The same three counters for the metafield WRAPPER SPEC SET, whose unit is the CELL and not a declaration: the
     * reconcile runs ONCE, lazily, on the first read after the pass, over every MODEL node and every STRUCT / CHOICE
     * node this pass saw. {@code stats()[0]} counts the SPEC KEYS compared, so the host's
     * {@code specs == expected} is the population assertion the other lines make with {@code declarations}.
     */
    public int[] wrapperReconcileStats() {
        reconcileWrappersOnce();
        return wrapperReconciler.stats();
    }

    /**
     * The wrapper spec count the OLD generator collects for this cell ({@code MetaFieldGenerator.collectSpecs().size()}),
     * read off the reconciler. The D11 host recomputes the same number for itself and asserts the two EQUAL - the host's
     * population must not be the generator's word for it (LAW 84).
     */
    public int wrapperExpected() {
        return wrapperReconciler.expected();
    }

    /**
     * The mismatch messages of the once-per-cell wrapper reconcile. They are raised by no generation call (the reconcile
     * runs after the pass, when the host first reads it), so the host prints them by name before it judges the line.
     */
    public List<String> wrapperMismatches() {
        reconcileWrappersOnce();
        return List.copyOf(wrapperReconcileMismatches);
    }

    /**
     * {@code {aliasConditionClasses, castType, qualifyFunctions, deepPathDependencies, deepPathArms}} - the fact
     * families v3.3 seat 9, PR #645 commits 12, 13 and 14 ADD to the derived reconcile. The D11 DERIVED line
     * prints {@code factsAsserted=<total> (carried=<old> + aliasConditionClasses=<n1> + castType=<n2> +
     * qualifyFunctions=<n3> + deepPathDependencies=<n4> + deepPathArms=<n5>)} and holds {@code carried},
     * {@code n1}, {@code n2} and {@code n3} at the commit-13 figures of the cell.
     */
    public int[] derivedNewFactCounts() {
        return derivedReconciler.newFactCounts();
    }

    /**
     * {@code {type-format checks, cardinality checks, only-exists members}} the derived reconcile's OWN IR-side walk
     */
    public int[] derivedCheckCounts() {
        return derivedReconciler.checkCounts();
    }

    /**
     * The type-format checks the IR half walked PER ELEMENT (keyed by the node's qualified name): the host's
     * {@code DERIVED TWO-READS} line subtracts the elements whose validator the generator REFUSED - a refusal withholds
     * a WHOLE file - and holds the written text against the remainder, the decode probe's own closure
     * ({@code text + refusedChecks == irWalk}).
     */
    public java.util.Map<String, Integer> derivedTypeFormatChecksByElement() {
        return derivedReconciler.typeFormatChecksByElement();
    }

    /**
     * THE POJO SHADOW RENDERS of every {@code data} declaration this pass saw (v3.3 seat 9, PR #645 commit 4), keyed
     * by the POJO's OUTPUT KEY. Each value is a two- or three-element array the D11 host reads REFLECTIVELY, in the
     * shape the other seams take, so the host stays decoupled from {@code rune-ir-java}'s types:
     * <ul>
     *   <li>{@code {"RENDERED", <the file text>, <SECTION:line,... >}} - the emitter wrote the whole file; the third
     *       element gives the 1-based line at which each section starts, so the host can name the SECTION a first
     *       differing line falls in;</li>
     *   <li>{@code {"PARTIAL", <SECTION>, <the rendered prefix text>, <SECTION:line,… >}} - the emitter stopped at a
     *       section it does not render yet, and hands back the FILE AS IT STOOD (v3.3 seat 9, PR #645 commit 5): the
     *       frame, the imports and every section that did render, with that text's own section line starts. The host
     *       compares the prefix with the golden's first N lines and books {@code prefixIdentical} /
     *       {@code prefixDiffering}. The two trailing elements are absent when the stop carried no prefix - a
     *       section method called on its own - so the host must read the LENGTH, never assume it;</li>
     *   <li>{@code {"REFUSED", <reason>}} - the emitter, the property model or the index refused the type by name.</li>
     * </ul>
     * SINCE COMMIT 9 every section of the POJO renders, so an entry is RENDERED unless the emitter, the property
     * model or the index refused the type by name - the PARTIAL shape stays because a section the emitter does
     * not render would still stop it there. Since commit 11 the POJO member is READY, so the host's line is that
     * member's GATE: its own population, {@code differing == 0} against the old generator's own render of the
     * cell, and {@code identical + noGolden == types} (PR #645 round 1 cq SF-1).
     */
    public java.util.Map<String, String[]> pojoShadowRenders() {
        // IN THE ORDER THE PASS BOOKED THEM, not Map.copyOf's - the same MEASURED reason as
        // IRUnitPass.unitShadowRenders (v3.3 seat 9, PR #645 commit 14): the host draws its five no-golden and
        // five divergence samples in this map's iteration order, and Map.copyOf salts that per JVM run, so two
        // runs of ONE head printed two different five-line samples under identical counts. No count and no byte
        // depends on the order; a diffable print does.
        return java.util.Collections.unmodifiableMap(new java.util.LinkedHashMap<>(pojoShadow));
    }

    /**
     * THE MEMBERS THE WIRING DECLARES READY - ONE DECLARATION FOR ALL SIX PASSES (v3.3 seat 9, PR #645 commit 12):
     * it lives on {@link IRTypeUnitWiring}, which the five per-kind derived generators read too, so the
     * all-or-nothing law cannot be true of one pass and false of another because five copies of a literal drifted.
     * This alias keeps the name the commit-11 test asserts on.
     */
    static final Set<IRTypeUnit.Member> READY_MEMBERS = IRTypeUnitWiring.READY_MEMBERS;

    /** The output keys of every file the type unit wrote on this route - empty until the unit is AVAILABLE. */
    private final Set<String> unitWritten = new java.util.LinkedHashSet<>();
    /** Every type NAME the production path asked the unit for, across this pass's models (the host's verdict line). */
    private final Set<String> unitAttempted = new java.util.TreeSet<>();
    /** Every type NAME the production path REFUSED, across this pass's models (the host's verdict line). */
    private final Set<String> unitRefused = new java.util.TreeSet<>();

    /**
     * THE PER-PASS EMITTER MEMO, KEYED BY THE VERSION STAMP (v3.3 seat 10, PR #646 commit 3 - PR #645 round 1
     * cq NIT-1), the POJO pass's half of {@link IRUnitPass}'s. The six emitters are built ONCE PER STAMP rather
     * than once per model, because an emitter is a pure function of this pass's index, its model index, the
     * generator model's pruning set, the type util and the stamp - see {@link IRTypeUnitWiring#membersFor} for the
     * law and for why the shared {@link IRDerivedFacts} is sound and may not be static. It lives on THIS generator,
     * beside the index it was built over.
     */
    private final Map<String, Map<IRTypeUnit.Member, IRTypeUnit.MemberEmitter>> membersByStamp =
            new java.util.HashMap<>();

    /**
     * THE SHADOW'S OWN POJO EMITTER, memoised by the same stamp on this generator (v3.3 seat 10, PR #646 commit 3).
     * It stays a SEPARATE construction from the unit's POJO emitter above - PR #645 round 1 cq SF-1 kept the two
     * apart on purpose, so the shadow measures a second build of the same pure function rather than the very
     * instance the route writes with. The finding asks only that neither be rebuilt PER MODEL.
     */
    private final Map<String, IRDataTypeEmitter> shadowEmitterByStamp = new java.util.HashMap<>();

    /**
     * The data-type emitter for one model's version. Since commit 12 {@link #unitFor} delegates to
     * {@link IRTypeUnitWiring#unitFor}, which constructs its OWN emitter, while {@link #shadowPojos} builds a
     * second through this method - so ONE instance no longer serves both (PR #645 round 1 cq SF-1). What holds is
     * what the file identity needs: the two constructions are the SAME PURE FUNCTION of the same inputs (the
     * index, the version, the doNotPrune set, the type util), and the D11 host's TYPE UNIT VERDICTS line asserts
     * the six passes' verdict sets EQUAL BY NAME - so the file the shadow measures is the file the unit writes.
     *
     * <p>Since v3.3 seat 10, PR #646 commit 3 it is MEMOISED BY THE STAMP on this pass
     * ({@link #shadowEmitterByStamp}) instead of built per model - still a second construction, still never the
     * unit's instance. Package-private since commit 4: {@link IRChoiceObjectGenerator} shadows the CHOICES
     * through THIS emitter over THIS pass's index, so the choice half of the POJO shadow is the same
     * construction as the data types' half and not a seventh one.
     */
    IRDataTypeEmitter emitterFor(String version) {
        return shadowEmitterByStamp.computeIfAbsent(IRTypeUnitWiring.stamp(version),
                stamp -> new IRDataTypeEmitter(index,
                        new IRDataTypeEmitter.Config(stamp, generatorModel.doNotPrune()),
                        typeUtil));
    }

    /**
     * THE PASS'S OWN WORKSPACE-WIDE TYPE INDEX - ONE node per declaration (v3.3 seat 10, PR #646 commit 4). The
     * same package-private seam {@link IRUnitPass#index()} opens on the five derived passes, opened here for
     * {@link IRChoiceObjectGenerator}: the choice POJO shadow runs on THIS pass's index and THIS pass's memoised
     * shadow emitter, because a node from another adapter is not the instance this pass's halves compare.
     */
    IRTypeIndex index() {
        return index;
    }

    /**
     * The type unit for one model's version, with exactly {@link #READY_MEMBERS} declared ready - built by
     * {@link IRTypeUnitWiring}, the ONE construction all six passes take, so the file the D11 SHADOW measures is
     * the file the unit would write. SINCE COMMIT 15 all six members are in the map and
     * {@link IRTypeUnitWiring#AVAILABLE} is true, so {@link IRTypeUnit#available()} is true and
     * {@link IRTypeUnit#verdict} writes every data type whole or refuses it whole BY NAME (PR #645 round 1
     * cq SF-1).
     *
     * <p>Its six EMITTERS come from {@link #membersByStamp}, built once per version stamp on this pass (v3.3 seat
     * 10, PR #646 commit 3); the UNIT is still fresh per call, because its per-node memo and its attempted /
     * refused sets are per-unit state.
     */
    IRTypeUnit unitFor(String version) {
        String stamp = IRTypeUnitWiring.stamp(version);
        return IRTypeUnitWiring.unitFor(membersByStamp.computeIfAbsent(stamp,
                s -> IRTypeUnitWiring.membersFor(index, modelIndex, generatorModel, typeUtil, s)));
    }

    /**
     * SEAM for the D11 host (read reflectively, like {@link #pojoShadowRenders}): the members the wiring declares
     * ready, as their names. When the POJO is among them the host asserts the shadow line as the member's gate.
     */
    public Set<String> unitReady() {
        return IRTypeUnitWiring.readyNames();
    }

    /**
     * SEAM for the D11 host (read reflectively, beside {@link #unitReady()}): the WIRING'S OWN {@code AVAILABLE}
     * switch (v3.3 seat 9, PR #645 commit 14). Ready and available are TWO facts, and the host's
     * {@code UNIT READY} line prints both - a line that said only "6 of 6" would read as a route that is on.
     */
    public boolean unitAvailable() {
        return IRTypeUnitWiring.available();
    }

    /**
     * SEAM for the D11 host (read reflectively, beside {@link #unitAvailable()}): the WIRING'S KIND-SCOPED switch
     * for the CHOICE kind (v3.3 seat 10, PR #646 commit 4). READY, AVAILABLE and CHOICE_AVAILABLE are THREE facts
     * and the host's {@code UNIT READY} line prints all three - a line that said only "6 of 6 ; AVAILABLE=true"
     * would read as a route that writes the choices - which it does since PR #646 commit 5, the kind switch ON
     * (this sentence read "and at this commit it does not" from commit 4 to commit 8; round 1 cq SF-1).
     */
    public boolean unitChoiceAvailable() {
        return IRTypeUnitWiring.choiceAvailable();
    }

    /** SEAM for the D11 host: every type NAME the production path asked this pass's unit for. */
    public Set<String> unitAttemptedTypes() {
        return Set.copyOf(unitAttempted);
    }

    /** SEAM for the D11 host: every type NAME this pass's unit REFUSED. */
    public Set<String> unitRefusedTypes() {
        return Set.copyOf(unitRefused);
    }

    @Override
    public Set<String> filesWrittenByIrEmitter() {
        return Set.copyOf(unitWritten);
    }

    @Override
    public List<GenerationException> generateClassesAsIR(RModel model, String version,
                                                         Map<String, String> output) {
        List<GenerationException> errors = new ArrayList<>(reconcile(model));
        IRTypeUnit unit = unitFor(version);
        if (unit.available()) {
            // THE UNIT'S OWN PATH, PER MEMBER (v3.3 seat 9, PR #645 commit 12 - the planning review's Q5; written
            // at commit 11 and reached only when the sixth member is declared ready). This pass owns ONE member of
            // the six - the POJO - and writes ONLY its key: the other five belong to the five per-kind derived
            // generators, each reading ITS OWN unit over the same node, and a pass that wrote all six would put a
            // file into the output map its own kind never owned (the "a file has ONE writer" law the D11 asserts).
            //
            // A REFUSAL IS A WHOLE-ELEMENT DECISION: the INHERITED generator's path runs for THAT element, so the
            // old generator's file AND its own errors are produced exactly as on the OFF route. The refusal itself
            // never lands in `errors` - it is this route's reason for taking the other path, not a failure of its
            // own (commit 11 booked it as a generation error and wrote nothing for the type, which would have left
            // a hole where the OFF route writes a file).
            // EVERY element the loop below walked for, in the order it walked them - the input to the population
            // assertion that replaces the old non-data-type split (v3.3 seat 9, PR #645 commit 15)
            List<RRootElement> walked = new ArrayList<>();
            // ONE ELEMENT LOOP FOR SEVEN CALLERS, on IRUnitPass (v3.3 seat 10, PR #646 commit 5 - LAW 69, the
            // commit-3 lift of `inherited` grown to the whole routing law, because the choice route needs the
            // SAME loop over a second population). The two lambdas hand the collaborator THIS generator's
            // createTypeRepresentation and generate, so a refused element's bytes and its errors are the OFF
            // route's exactly as before.
            //
            // THE POPULATION HANDED IN IS THIS GENERATOR'S OWN RE-DERIVATION of the inherited filter - the data
            // types - and NOT `streamObjects(model)`: the assertion below holds the walk against streamObjects's
            // own yield: the two filters are the same filter, and what the assertion witnesses is the LOOP'S WALK
            // against that population - every element walked once, in order, none skipped (lane P1's hole).
            // The choices are IRChoiceObjectGenerator's population on its own pass; a loop that walked them here
            // would put a file into the output map this pass's kind never owned.
            String namespace = model.namespace();
            List<RRootElement> mine = new ArrayList<>();
            for (RRootElement element : model.rootElements()) {
                if (element instanceof RDataType) {
                    mine.add(element);
                }
            }
            errors.addAll(IRUnitPass.routeElements(unit, mine, namespace, version, index,
                    IRTypeUnit.Member.POJO, output, unitWritten, walked,
                    e -> createTypeRepresentation((RDataType) e),
                    (e, r, v) -> generate((RDataType) e, (RJavaPojoInterface) r, v)));
            bookUnitVerdicts(unit);
            assertUnitLoopCoversTheInheritedPopulation(model, walked);
        } else {
            errors.addAll(generateClasses(model, version, output));
        }
        shadowPojos(model, version);
        return errors;
    }

    /**
     * BOOK A UNIT'S VERDICT SETS INTO THIS PASS'S OWN (v3.3 seat 10, PR #646 commit 5). The POJO member is ONE
     * member of the unit and the D11 host reads its {@code attempted} / {@code refused} sets off THIS generator -
     * but since this commit the member is routed by TWO generators, this one over the data types and
     * {@link IRChoiceObjectGenerator} over the choices, each with its own unit instance over the same index and
     * the same memoised emitters. A member's verdict set is the MEMBER'S, not a generator's, so the choice pass
     * books here too and the host's {@code TYPE UNIT VERDICTS} line sees the whole population of the pass.
     */
    void bookUnitVerdicts(IRTypeUnit unit) {
        unitAttempted.addAll(unit.attemptedTypes());
        unitRefused.addAll(unit.refusedTypes());
    }

    /**
     * THE NON-DATA-TYPE SPLIT, WHICH IS EMPTY BY CONSTRUCTION (v3.3 seat 9, PR #645 commit 15 - the switch commit).
     *
     * <p>Until this commit the unit's own path ended in a stated throw, because nobody had established which of the
     * inherited generator's files are the data types' and which are not. The answer is READ from the inherited
     * generator itself: {@code ModelObjectGenerator.streamObjects}
     * ({@code rune-java-generator/src/main/java/com/regnosys/rosetta/generator/java/object/ModelObjectGenerator.java:68-71})
     * is {@code model.rootElements().stream().filter(e -> e instanceof RDataType)} and NOTHING else - the choices
     * are {@code ChoiceObjectGenerator}'s population, on its own pass. So the inherited loop
     * ({@code JavaClassGenerator.generateClasses:58-76}) has NO non-data-type half: there is nothing left for this
     * method to write, and it writes NOTHING.
     *
     * <p>What it does instead is ASSERT that emptiness rather than assume it. It re-derives the inherited
     * generator's OWN population by calling {@code streamObjects} - the same method the inherited loop calls, not a
     * copy of its filter - and holds it EQUAL, element for element and IN ORDER, to the elements the unit's loop
     * above walked (each of which was either written from its verdict or taken through
     * {@link IRUnitPass#inherited}, the ONE declaration of the inherited per-element path since v3.3 seat 10,
     * PR #646 commit 3).
     * A disagreement THROWS BY NAME, and it can only be one of two defects:
     * <ul>
     *   <li>an element {@code streamObjects} yields that the unit's loop never saw - a HOLE: a file the OFF route
     *       writes and this route would not;</li>
     *   <li>an element the loop saw that {@code streamObjects} would not yield - a file with TWO writers.</li>
     * </ul>
     * Neither is visible to a byte gate whose goldens another pass happens to write, which is why both are named
     * here rather than left to a count.
     *
     * @param walked the data types the unit's loop walked, in loop order
     */
    private void assertUnitLoopCoversTheInheritedPopulation(RModel model, List<RRootElement> walked) {
        assertUnitLoopCoversTheInheritedPopulation(model.namespace(), streamObjects(model).toList(), walked);
    }

    /**
     * THE SEAM of the assertion above (package-private): the two populations, HANDED IN. The production overload
     * reads the inherited half off {@code streamObjects}; a test drives THIS one with populations it builds, so the
     * hole arm and the double-writer arm are witnessed without mutating any production state.
     *
     * <p>SINCE v3.3 seat 10, PR #646 commit 5 it is ONE DECLARATION FOR TWO POPULATIONS (LAW 69):
     * {@link IRChoiceObjectGenerator} holds ITS walk against {@code ChoiceObjectGenerator.streamObjects} - the
     * choices of the model, in order - through this same seam. The law is the same law one kind over, so the
     * elements are {@link RRootElement}s and their names come from {@link IRUnitPass#declaredName}.
     *
     * @param modelNamespace the model the two populations belong to - named in every message
     * @param inheritedPopulation what {@code ModelObjectGenerator.streamObjects} yields for that model
     * @param walked the elements the unit's loop walked, in loop order
     */
    static void assertUnitLoopCoversTheInheritedPopulation(String modelNamespace,
            List<? extends RRootElement> inheritedPopulation, List<? extends RRootElement> walked) {
        String where = "IR type unit: the model " + modelNamespace + " - ";
        int common = Math.min(inheritedPopulation.size(), walked.size());
        for (int i = 0; i < common; i++) {
            RRootElement inherited = inheritedPopulation.get(i);
            RRootElement seen = walked.get(i);
            if (inherited != seen) {
                throw new IllegalStateException(where + "the unit's loop and the inherited generator's own"
                        + " population DISAGREE at index " + i + ": streamObjects yields '"
                        + IRUnitPass.declaredName(inherited) + "' where the loop walked '"
                        + IRUnitPass.declaredName(seen) + "'. The POJO pass writes its own kind's declarations and"
                        + " the inherited generator writes nothing beside them, so the two walks are ONE walk or"
                        + " one of them is wrong");
            }
        }
        if (inheritedPopulation.size() > walked.size()) {
            throw new IllegalStateException(where + "the inherited generator would write "
                    + (inheritedPopulation.size() - walked.size()) + " declaration(s) the unit's loop never"
                    + " walked - a HOLE, a file the OFF route writes and this route would not: "
                    + names(inheritedPopulation.subList(walked.size(), inheritedPopulation.size())));
        }
        if (walked.size() > inheritedPopulation.size()) {
            throw new IllegalStateException(where + "the unit's loop walked "
                    + (walked.size() - inheritedPopulation.size()) + " element(s) the inherited generator's own"
                    + " population does not yield - a file with TWO writers: "
                    + names(walked.subList(inheritedPopulation.size(), walked.size())));
        }
    }

    /** The first few names of a population, for a refusal message. */
    private static String names(List<? extends RRootElement> elements) {
        List<String> named = new ArrayList<>();
        for (RRootElement element : elements) {
            if (named.size() == 5) {
                named.add("(+" + (elements.size() - 5) + " more)");
                break;
            }
            named.add(IRUnitPass.declaredName(element));
        }
        return named.toString();
    }

    /**
     * Ask {@link IRDataTypeEmitter} for a SHADOW render of every {@code data} declaration of this model, and book
     * what it answered. The shadow runs AFTER the pass's own generation and writes into no output map - it is a
     * measurement, not an emission, and a throw of any kind is BOOKED rather than raised, so a shadow can never
     * break a generation that the route would otherwise complete.
     *
     * <p>The PRUNING half of the emitter's config is the generator model's OWN {@code doNotPrune} set, read
     * through the seam {@code GeneratorModel.doNotPrune()} (v3.3 seat 9, PR #645 commit 9): section 12's
     * {@code prune()} and {@code hasData()} arms branch on it per {@code (type, attribute)} pair, exactly as
     * {@code ModelObjectGenerator:1315-1316} and {@code :1359-1360} do, and the D11 host has already fed this
     * generator model the cell's own entries from {@code rosetta-config.yml} - so nothing is re-read from the
     * yml and nothing is guessed. Commit 4's placeholder boolean, which no section read, is gone. The version is
     * the host's, per model, as every other emitter takes it.
     */
    private void shadowPojos(RModel model, String version) {
        IRDataTypeEmitter emitter = emitterFor(version);   // commit 11: the SAME construction the unit takes
        String namespace = model.namespace();
        for (RRootElement element : model.rootElements()) {
            if (!(element instanceof RDataType dataType)) {
                continue;
            }
            String key;
            IRTypeNode node;
            try {
                node = index.node(namespace, dataType);
                key = IRDataTypeEmitter.outputKey(node);
            } catch (RuntimeException e) {
                // the node or its key could not even be formed: book it under the DECLARATION's qualified name, so
                // the type is still counted and named rather than dropped from the shadow's population
                pojoShadow.put(namespace + "." + dataType.name() + " (no output key)",
                        new String[] {"REFUSED", IRUnitPass.reason(e)});
                continue;
            }
            try {
                IRDataTypeEmitter.Rendered rendered = emitter.renderWithSections(node);
                pojoShadow.put(key, new String[] {"RENDERED", rendered.text(),
                        renderSectionLineStarts(rendered.sectionLineStarts())});
            } catch (IRDataTypeEmitter.NotYetRendered partial) {
                // v3.3 seat 9 (PR #645 commit 5): a partial render hands back the prefix it DID produce, so the host
                // can hold it against the golden's first N lines. A stop with no prefix books the two-element form.
                pojoShadow.put(key, partial.prefix()
                        .map(prefix -> new String[] {"PARTIAL", partial.section().name(), prefix.text(),
                                renderSectionLineStarts(prefix.sectionLineStarts())})
                        .orElseGet(() -> new String[] {"PARTIAL", partial.section().name()}));
            } catch (RuntimeException e) {
                pojoShadow.put(key, new String[] {"REFUSED", IRUnitPass.reason(e)});
            }
        }
    }

    /** {@code SECTION:line,SECTION:line,…} - the host parses it to name the section a differing line falls in. */
    /**
     * <p>Package-private since v3.3 seat 10, PR #646 commit 4: {@link IRChoiceObjectGenerator} books the
     * SAME three entry shapes for the choices, and ONE declaration of this encoding serves both maps
     * (LAW 69) - two spellings would let the host's reader agree with one half and not the other.
     */
    static String renderSectionLineStarts(java.util.Map<String, Integer> lineStarts) {
        StringBuilder sb = new StringBuilder();
        for (java.util.Map.Entry<String, Integer> entry : lineStarts.entrySet()) {
            if (sb.length() > 0) {
                sb.append(',');
            }
            sb.append(entry.getKey()).append(':').append(entry.getValue());
        }
        return sb.toString();
    }

    /**
     * Build the STRUCT IR for each data type in the model - and the TYPE_ALIAS IR for each {@code typeAlias} - and
     * assert EVERY fact each carries against the source, each population through its own reconciler. Then (v3.3 seat 8,
     * PR #644) read the model's PROPERTY SURFACE and DERIVED FACTS for every validated element, and the MODEL node
     * itself, each through its own reconciler and its own counters.
     */
    List<GenerationException> reconcile(RModel model) {   // package-private: the throw witness calls the reconcile alone
        List<GenerationException> errors = new ArrayList<>();
        String namespace = model.namespace();
        for (var element : model.rootElements()) {
            if (element instanceof RDataType dataType) {
                reconciler.attempt();   // counted BEFORE the adapter: a throw below is a mismatch, never a silent drop
                try {
                    // the INDEX's instance (PR #644 round 1, cq SF-1): the declaration facts, the property surface and the
                    // derived facts are now asserted on ONE node - the one the property law's walks read - not on two equal ones
                    IRTypeNode ir = index.node(namespace, dataType);
                    for (String mismatch : reconciler.reconcileData(namespace, dataType, ir)) {
                        errors.add(new GenerationException(mismatch, null, dataType));
                    }
                } catch (RuntimeException e) {
                    reconciler.threw();
                    errors.add(new GenerationException(
                            "AST->IR adapter failed for data " + dataType.name(),
                            null, dataType, e));
                }
            } else if (element instanceof RTypeAlias alias) {
                aliasReconciler.attempt();   // its own population, counted BEFORE the adapter
                try {
                    // the alias reconciler's adapter IS the data reconciler's (shared at construction)
                    IRTypeNode ir = aliasReconciler.adapter().adaptTypeAlias(namespace, alias);
                    for (String mismatch : aliasReconciler.reconcileTypeAlias(namespace, alias, ir)) {
                        errors.add(new GenerationException(mismatch, null, alias));
                    }
                } catch (RuntimeException e) {
                    aliasReconciler.threw();
                    errors.add(new GenerationException(
                            "AST->IR adapter failed for typeAlias " + alias.name(),
                            null, alias, e));
                }
            }
        }
        errors.addAll(reconcileProperties(model, namespace));
        errors.addAll(reconcileModelNode(model));
        return errors;
    }

    /**
     * THE PROPERTY AND DERIVED READS (v3.3 seat 8, PR #644). One population - the cell's VALIDATED ELEMENTS, its
     * {@code data} types and its {@code choice}s together - read twice: once as the POJO property surface the type
     * emitter will write from, once as the input facts its per-type DERIVED files stand on. Both are booked BEFORE
     * either half runs, so an element whose property model REFUSES (the two named refusals of {@link IRPropertyModel})
     * or throws is a mismatch on BOTH lines rather than a declaration missing from a population. The nodes the reads
     * used are kept for the once-per-cell wrapper reconcile, which needs the whole cell before it can compare a set.
     */
    private List<GenerationException> reconcileProperties(RModel model, String namespace) {
        List<GenerationException> errors = new ArrayList<>();
        for (RRootElement element : model.rootElements()) {
            if (!(element instanceof RDataType) && !(element instanceof RChoice)) {
                continue;
            }
            propertyReconciler.attempt();
            derivedReconciler.attempt();   // ONE population: the derived read is owed for this element either way
            IRTypeNode node;
            IRPropertyModel properties;
            try {
                if (element instanceof RDataType dataType) {
                    node = index.node(namespace, dataType);
                    properties = IRPropertyModel.of(node, index);
                    for (String mismatch : propertyReconciler.reconcile(namespace, dataType, properties)) {
                        errors.add(new GenerationException(mismatch, null, dataType));
                    }
                } else {
                    RChoice choice = (RChoice) element;
                    node = index.node(namespace, choice);
                    properties = IRPropertyModel.of(node, index);
                    for (String mismatch : propertyReconciler.reconcile(namespace, choice, properties)) {
                        errors.add(new GenerationException(mismatch, null, choice));
                    }
                }
            } catch (RuntimeException e) {
                propertyReconciler.threw();
                // the derived facts stand ON the property model: no model, no read - and a read that never happened is
                // a mismatch here, never a quiet hole in the derived line's population
                derivedReconciler.threw();
                errors.add(new GenerationException(
                        "AST->IR property model failed for " + elementName(element), null, element, e));
                continue;
            }
            emittedTypeNodes.add(node);
            try {
                for (String mismatch : derivedReconciler.reconcile(namespace, element, node, properties, index)) {
                    errors.add(new GenerationException(mismatch, null, element));
                }
            } catch (RuntimeException e) {
                derivedReconciler.threw();
                errors.add(new GenerationException(
                        "IR derived-facts reconcile failed for " + elementName(element), null, element, e));
            }
        }
        return errors;
    }

    /** The MODEL node of this model, adapted through the pass's own adapter and asserted against its source. */
    private List<GenerationException> reconcileModelNode(RModel model) {
        List<GenerationException> errors = new ArrayList<>();
        modelReconciler.attempt();   // counted BEFORE the adapter, as every population here is
        try {
            IRModelNode node = modelIndex.node(model);   // the index's instance: adapted once, the same node every half reads
            emittedModelNodes.add(node);
            for (String mismatch : modelReconciler.reconcile(model, node)) {
                errors.add(new GenerationException(mismatch, null, model));
            }
        } catch (RuntimeException e) {
            modelReconciler.threw();
            errors.add(new GenerationException(
                    "AST->IR adapter failed for model " + model.namespace(), null, model, e));
        }
        return errors;
    }

    /**
     * The WRAPPER spec set is a fact of the whole CELL - a spec is claimed by the FIRST of four sources to reach its
     * dedup key, and two of those sources are function signatures and {@code with-meta} expressions, which no single
     * declaration carries. So the reconcile waits until the pass is over and runs ONCE, on the host's first read;
     * a throw is a mismatch and its message is the one the host prints.
     */
    private void reconcileWrappersOnce() {
        if (wrapperReconcileMismatches != null) {
            return;
        }
        try {
            wrapperReconcileMismatches = List.copyOf(
                    wrapperReconciler.reconcile(List.copyOf(emittedModelNodes), List.copyOf(emittedTypeNodes)));
        } catch (RuntimeException e) {
            wrapperReconciler.threw();
            wrapperReconcileMismatches = List.of("IR/AST reconciliation failed for WRAPPERS: the spec set could not be"
                    + " derived from the IR - " + e.getClass().getSimpleName() + ": " + e.getMessage());
        }
    }

    /** The declared name of a validated element, for a refusal message that names what it refused. */
    private static String elementName(RRootElement element) {
        return element instanceof RDataType dataType ? dataType.name() : ((RChoice) element).name();
    }
}
