package com.regnosys.rosetta.symbols;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Field;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.nio.file.*;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

/**
 * Walks every class under {@code com.regnosys.rosetta.ast.*} and produces a
 * deterministic textual representation of its public surface — class name,
 * superclass, public/protected fields (type + name), public/protected
 * methods (return type + name + parameter types).
 *
 * <p>Output is sorted at every level so the snapshot is byte-deterministic
 * across runs.
 *
 * <p>Spec: D5/E12 in {@code docs/specs/2026-04-07-m3-symbols-resolution-design.md}.
 */
public final class SchemaLockGenerator {

    /**
     * Cached module {@code target/classes/} root. Resolved once per JVM via
     * {@link #mainClassesRoot()} to avoid re-parsing the ProtectionDomain URI
     * and re-checking the filesystem for every package in {@link #AST_PACKAGES}.
     */
    private static final Path MAIN_CLASSES_ROOT = mainClassesRoot();

    /** Root packages to walk. */
    private static final List<String> AST_PACKAGES = List.of(
        "com.regnosys.rosetta.ast",
        "com.regnosys.rosetta.ast.annotations",
        "com.regnosys.rosetta.ast.enums",
        "com.regnosys.rosetta.ast.expressions.binary",
        "com.regnosys.rosetta.ast.expressions.constructors",
        "com.regnosys.rosetta.ast.expressions.literals",
        "com.regnosys.rosetta.ast.expressions.references",
        "com.regnosys.rosetta.ast.expressions.supporting",
        "com.regnosys.rosetta.ast.expressions.unary",
        "com.regnosys.rosetta.ast.external",
        "com.regnosys.rosetta.ast.functions",
        "com.regnosys.rosetta.ast.mapping",
        "com.regnosys.rosetta.ast.model",
        "com.regnosys.rosetta.ast.regulatory",
        "com.regnosys.rosetta.ast.supporting",
        "com.regnosys.rosetta.ast.synonyms",
        "com.regnosys.rosetta.ast.types",
        "com.regnosys.rosetta.ast.util"
    );

    public static String generate() {
        StringBuilder sb = new StringBuilder();
        sb.append("# M2 AST schema lock — generated by SchemaLockGenerator\n");
        sb.append("# Any change to this snapshot must be a deliberate, reviewed update.\n");
        sb.append("# Spec: D5/E12 in 2026-04-07-m3-symbols-resolution-design.md\n\n");

        List<Class<?>> all = AST_PACKAGES.stream()
            .flatMap(pkg -> classesIn(pkg).stream())
            .filter(c -> !c.isAnonymousClass() && !c.isLocalClass())
            .filter(c -> !c.getName().endsWith("Test"))       // exclude test classes
            .filter(c -> !c.getName().contains("$"))          // exclude inner classes
            .sorted(Comparator.comparing(Class::getName))
            .toList();

        for (Class<?> c : all) {
            describeClass(c, sb);
            sb.append('\n');
        }
        return sb.toString();
    }

    private static void describeClass(Class<?> c, StringBuilder sb) {
        sb.append("class ").append(c.getName());
        if (c.getSuperclass() != null && c.getSuperclass() != Object.class) {
            sb.append(" extends ").append(c.getSuperclass().getName());
        }
        sb.append(" {\n");

        // Fields — public + protected only
        List<Field> fields = Arrays.stream(c.getDeclaredFields())
            .filter(f -> Modifier.isPublic(f.getModifiers()) || Modifier.isProtected(f.getModifiers()))
            .sorted(Comparator.comparing(Field::getName))
            .toList();
        for (Field f : fields) {
            sb.append("  field ").append(typeName(f.getGenericType()))
              .append(" ").append(f.getName()).append("\n");
        }

        // Constructors — public + protected only
        List<Constructor<?>> ctors = Arrays.stream(c.getDeclaredConstructors())
            .filter(ct -> Modifier.isPublic(ct.getModifiers()) || Modifier.isProtected(ct.getModifiers()))
            .sorted(Comparator.comparing(ct -> paramSig(ct.getParameterTypes())))
            .toList();
        for (Constructor<?> ct : ctors) {
            sb.append("  ctor (").append(paramSig(ct.getParameterTypes())).append(")\n");
        }

        // Methods — public + protected, declared on this class only
        List<Method> methods = Arrays.stream(c.getDeclaredMethods())
            .filter(m -> Modifier.isPublic(m.getModifiers()) || Modifier.isProtected(m.getModifiers()))
            .filter(m -> !m.isSynthetic() && !m.isBridge())
            .sorted(Comparator.<Method, String>comparing(Method::getName)
                              .thenComparing(m -> paramSig(m.getParameterTypes())))
            .toList();
        for (Method m : methods) {
            sb.append("  method ").append(typeName(m.getGenericReturnType()))
              .append(" ").append(m.getName())
              .append("(").append(paramSig(m.getParameterTypes())).append(")\n");
        }

        sb.append("}\n");
    }

    private static String typeName(java.lang.reflect.Type t) {
        return t.getTypeName();
    }

    private static String paramSig(Class<?>[] params) {
        return Arrays.stream(params).map(Class::getName).collect(Collectors.joining(", "));
    }

    /**
     * Enumerates classes in a package by walking the {@code target/classes/} filesystem
     * directly. This avoids a classloader URL-ordering bug: when a test-scope subpackage
     * exists (e.g. {@code target/test-classes/com/regnosys/rosetta/ast/annotations/}
     * containing {@code RRuneAnnotationContractTest.class}), the classloader's
     * {@code getResource(...)} would return that URL first, causing the scan to miss
     * the main classes in {@code target/classes/com/regnosys/rosetta/ast/annotations/}.
     *
     * <p>Scanning {@code target/classes/} directly makes the AST-shape lock independent
     * of test-class proximity. Test classes are explicitly excluded from the snapshot
     * via the {@code !c.getName().endsWith("Test")} filter in {@link #generate()}, so
     * we never need to walk test-classes here.
     *
     * <p>The {@code target/classes/} location is resolved by deriving the module's
     * build-output directory from {@link SchemaLockGenerator}'s {@code ProtectionDomain}
     * rather than relying on the JVM working directory. This makes the scan correct
     * under Surefire {@code forkCount=0} (in-process tests) and when {@code mvn} is run
     * from a parent directory (e.g. {@code mvn -f rune-parser/pom.xml test} from
     * the repo root), where {@code Paths.get("target/classes")} would otherwise
     * silently resolve to a non-existent path and the scan would return empty.
     */
    private static List<Class<?>> classesIn(String packageName) {
        Path mainClassesDir = MAIN_CLASSES_ROOT.resolve(packageName.replace('.', '/'));
        if (!Files.isDirectory(mainClassesDir)) {
            return List.of();
        }
        try (Stream<Path> stream = Files.list(mainClassesDir)) {
            List<Class<?>> result = new ArrayList<>();
            stream
                .filter(p -> p.getFileName().toString().endsWith(".class"))
                .map(p -> p.getFileName().toString().replace(".class", ""))
                .filter(name -> !name.contains("$"))
                .forEach(name -> {
                    try {
                        result.add(Class.forName(packageName + "." + name));
                    } catch (ClassNotFoundException e) {
                        throw new RuntimeException("failed to load " + packageName + "." + name, e);
                    }
                });
            return result;
        } catch (IOException e) {
            throw new RuntimeException("failed to list " + packageName, e);
        }
    }

    /**
     * Resolves the module's {@code target/classes/} directory by walking up from
     * the location of {@link SchemaLockGenerator}'s own classfile (under
     * {@code target/test-classes/}) to its sibling {@code target/classes/}.
     * Independent of JVM working directory; correct under Surefire forking
     * variants and when Maven is invoked from a parent directory.
     *
     * @throws IllegalStateException if the resolved path is not a directory
     *     (signals a build-layout assumption violation, not a silent fallthrough)
     */
    private static Path mainClassesRoot() {
        try {
            Path testClassesRoot = Paths.get(
                    SchemaLockGenerator.class.getProtectionDomain()
                            .getCodeSource()
                            .getLocation()
                            .toURI());
            Path candidate = testClassesRoot.resolveSibling("classes");
            if (!Files.isDirectory(candidate)) {
                throw new IllegalStateException(
                        "Expected main classes dir at " + candidate +
                                " (sibling of test-classes root " + testClassesRoot +
                                ") — build layout assumption violated");
            }
            return candidate;
        } catch (java.net.URISyntaxException e) {
            throw new IllegalStateException("failed to resolve test-classes root", e);
        }
    }
}
